### ISSUE TITLE
different font glyph display

### ISSUE THREAD

**Issue by coolit** [imgui-rs/imgui-rs#157]
In imgui, it seems only several font glyph types supported. Does this mean that, you can not display all kinds of utf8 characters at the same time?  But oftentimes, you may need to display Chinese, Thai, etc. at the same time.  Is this possible with Imgui?

**Comment by Gekkio** [comment]
I haven't tried it myself, but I think it should be possible to use `FontGlyphRange::from_slice` to generate a set of unicode glyph ranges, including for example Chinese and Thai at the same time. If you then have a font that has all these glyphs, I think it should work.

For example, something like this (not actually tested):

```rust
let range = FontGlyphRange::from_slice(&[
  0x0020, 0x00FF, // Basic Latin + Latin Supplement
  0x2010, 0x205E, // Punctuations
  0x0E00, 0x0E7F, // Thai
  0x3000, 0x30FF, // Punctuations, Hiragana, Katakana
  0x31F0, 0x31FF, // Katakana Phonetic Extensions
  0xFF00, 0xFFEF, // Half-width characters
  0x4e00, 0x9FAF, // CJK Ideograms
  0,
])
```

**Comment by francesco-cattoglio** [comment]
I know this is a 2 years old issue, but I can confirm this works in 0.5:
```
    let custom_ranges = FontGlyphRanges::from_slice(&[
        0x0020, 0x00FF, // Basic Latin + Latin Supplement
        0x2200, 0x22FF, // a range that contains some miscellaneous symbols
        0x2600, 0x26FF, // another range with miscellaneous symbols
        0]); // this 0 is required to close the ranges list

    imgui_context.fonts().add_font(&[FontSource::TtfData {
        data: include_bytes!("../some/nice/font.ttf"),
        size_pixels: my_font_size,
        config: Some(imgui::FontConfig {
            glyph_ranges: custom_ranges,
            size_pixels: my_font_size,
            ..Default::default()
        }),
    }]);
```
The font must contain the character (or emoji) in the provided custom ranges. You can verify that with a tool like fontforge (which also allows you to edit the ttf font in case you need it!).
