### ISSUE TITLE
GetForegroundDrawList and GetBackgroundDrawList not exposed (upgrade Dear Imgui to 1.69)

### ISSUE THREAD

**Issue by hrydgard** [imgui-rs/imgui-rs#220]
These were recently exposed in Dear Imgui (https://github.com/ocornut/imgui/issues/2391, https://github.com/ocornut/imgui/releases) and are very useful - would be nice to have exposed in imgui-rs.

I guess this is a result of this being based on 1.66b while Dear Imgui is now at 1.69 (and so is cimgui).

**Comment by tangmi** [comment]
FYI it looks like `imgui-rs` has been upgraded to 1.69 on the 0.1-dev branch (https://github.com/Gekkio/imgui-rs/commit/a79cd06cb2a4aee02b7a55c9a39553e0811b6f10)! The two draw list methods don't look like they've been exposed, but shouldn't be super difficult to do.

**Comment by tangmi** [comment]
Made much more progress with #242

**Comment by saucesaft** [comment]
I also would like for this functions to be exposed, what can I do to help?

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by tangmi** [comment]
I personally haven't touched it in a while, but I think if we can resolve the outstanding issues on #242, we can get Gekkio to review.

**Comment by tangmi** [comment]
This can probably be closed, these functions were added in #414!

**Comment by sanbox-irl** [comment]
Thank you for the common! Going to close as we've now gotten it in
