### ISSUE TITLE
ImageButton and textures with gfx

### ISSUE THREAD

**Issue by iolivia** [imgui-rs/imgui-rs#224]
I've been digging through the source code and examples but I cannot seem to find how to create an image button with a texture with gfx. I've seen the glium one but I'm not really sure how it would translate to gfx.

**Comment by Gekkio** [comment]
There's now a custom texture example for gfx in master. Basically with the gfx renderer a "texture" is a `(texture_view, sampler)` tuple that you can construct if you have access to the `gfx::Factory`.

**Comment by iolivia** [comment]
Thank you, I will give that a go 😄

**Comment by MichaelMauderer** [comment]
It might be valuable to also add an example of a texture that is updated dynamically on every frame.

**Comment by dbr** [comment]
Closign old ticket; gfx renderer is now archived (although the texture examples could still use improvements, the current examples have a lot of boilerplate per-texture)
