### ISSUE TITLE
Can I use this crate in d3d11 present hook?

### ISSUE THREAD

**Issue by AurevoirXavier** [imgui-rs/imgui-rs#226]
Now, I got the `IDXGISwapChain` pointer (and everything needed). 
What should I do to start drawing a imgui?

In C++:

```c++
ImGui_ImplWin32_Init(sd.OutputWindow);
ImGui_ImplDX11_Init(pDevice, pContext);
```

**Comment by Gekkio** [comment]
`ImGui_ImplWin32_Init` and `ImGui_ImplDX11_Init` are both just example implementations in Dear ImGui and are not part of the main library. It sounds like you're not using the existing renderers of imgui-rs? In that case you need to write the renderer and possibly platform code from scratch.

**Comment by AurevoirXavier** [comment]
Yes you're right. So I have to implement them manually with Low-level API(imgui-sys)?
