### ISSUE TITLE
Consider using `mint` in the place of `ImVec2`, etc

### ISSUE THREAD

**Issue by tangmi** [imgui-rs/imgui-rs#231]
I agree with https://github.com/Gekkio/imgui-rs/pull/61#issuecomment-313841337 that it doesn't make sense in all usages of `ImVec` to have general math operations implemented, but we should consider using [`mint`](https://crates.io/crates/mint) ("math interoperability standard types").

This would make it much easier to use (and leverage the math operations from) libraries like `euclid`, `cgmath`, `nalgebra`, etc with `imgui-rs`, as they all implement conversions to `mint` types.

```rust
let window_size = euclid::TypedSize2D::new(800.0, 600.0);
let extra = euclid::TypedSize2D::new(50.0, 50.0);

// pub fn size(mut self, size: mint::Vector2<f32>, condition: Condition) -> ...
Window::new(im_str!("Hello world"))
    .size((window_size + extra).into(), Condition::Once)
    .build(&ui, || {});
```

**Comment by Gekkio** [comment]
0.1 abolishes `ImVec2` and `ImVec4` from safe APIs and simple arrays are used instead (`[f32; 2]`, `[f32; 4]`). This should make things easier in general, and I imagine libraries usually provide conversions to/from these kind of arrays if you want to do more complicated stuff.

**Comment by tangmi** [comment]
Sounds good to me, it looks like at least `euclid`, `cgmath`, `nalgebra`, and `gfx` support `impl Into<[f32; ...]> for ...` most of their types.

There may still be an argument to use `mint` still to have a distinction between a `[f32; 2]` representing a "point" and a `[f32; 2]` representing a "vector", etc, but feel free to close this.

**Comment by tangmi** [comment]
Closing since Gekkio's resolution works for me!
