### ISSUE TITLE
High CPU usage while nothing is changed in window or user input

### ISSUE THREAD

**Issue by xrombik** [imgui-rs/imgui-rs#241]
High CPU usage while nothing is changed in window or user input. On my system i have about 10% CPU load while program from examples is running:
```
cargo run --example test_window
```
My system is:
OS: Linux Mint 19.1
Desktop: XFCE, x64.
CPU: Intel E5450 3.78GHz,
video: Radeon R270.

**Comment by Gekkio** [comment]
This is perfectly normal. Immediate mode GUIs construct the entire GUI on every frame, and you're running the example in debug mode. On my system I get ~10-12 % CPU usage in debug mode and <5 % CPU usage in release mode.

**Comment by xrombik** [comment]
Thank you for your reply. Is I'm right, if I think that Intel Atom processors are not powerful enough for `imgui-rs`?

**Comment by coolit** [comment]
In my case, the test-window program used 30-60% out of 2.4GHz cpu, depending on the area visible. Same under release mode. Is there anything I can set to fix this high CPU usage?

**Comment by luke-titley** [comment]
Check how your event loop has been setup. You don't want to be drawing when nothing has changed. The examples even in the dearimgui repo, typically show the ui drawing all the time (like a game). But if you're making a tool that only changes on mouse/keyboard input then you'll save cpu by making sure you don't re-paint when nothing changes. This all happens in winit event loop if that's what your working with.

**Comment by tdryer** [comment]
Here's a modified version of [the example support code](https://github.com/Gekkio/imgui-rs/blob/132c749239779eb475a0a0cfa970b13d545112f7/imgui-examples/examples/support/mod.rs) that makes the examples only redraw after an event occurs:
https://gist.github.com/tdryer/5493a4cb28bb1e993216ace3102d07f8
