### ISSUE TITLE
Backspace no longer works on v0.1.0

### ISSUE THREAD

**Issue by nvll** [imgui-rs/imgui-rs#247]
I recently updated my code from using a pinned 0.0.23 to 0.1.0 and noticed backspace no longer works in a text input field to delete single characters, but it can delete the enter block of text if selected. I see the same behavior running the test_window_impl example in v0.1.0's imgui-examples directory. In case it matters, this is an older (2013) macbook pro keyboard with a US layout.

Looking at the new support code, it may be related to the Winit support? The 0.0.23 version I used called a method called 'configure_keys()' which doesn't seem to be used in the newer examples, but the current imgui_winit_support docs seem to indicate that has been rolled into init()?. I appreciate any help, and the work you've done so far!

**Comment by nvll** [comment]
Interesting, I found it works if I hold 'ctrl' while pressing backspace now.

**Comment by nvll** [comment]
Looking at the new support code, it may be related to the Winit support? The 0.0.23 version I used called a method called 'configure_keys()' which doesn't seem to be used in the newer examples.

**Comment by nvll** [comment]
On further testing, it still works on my Windows system.

**Comment by sanboxrunner** [comment]
Perhaps a different issue, but bakcspaces in input_float don't appear to be working, and imgui appears to be getting my backspaces and deletes. Even if I remove it from the receivedchar, I still can't get it to register em

**Comment by bjadamson** [comment]
I'm still running into this (on windows), is anyone else?
