### ISSUE TITLE
get_frame_count

### ISSUE THREAD

**Issue by 0b01** [imgui-rs/imgui-rs#255]
get_frame_count is now deprecated in favor of frame_count but there is no way to safely get a context.

It appears that frame_count does not need &Context: https://docs.rs/imgui/0.1.0/src/imgui/lib.rs.html#102-104

**Comment by Gekkio** [comment]
> there is no way to safely get a context.

But you need a context to call almost all imgui-rs functions...?

[The upstream C++ function](https://github.com/ocornut/imgui/blob/v1.71/imgui.cpp#L3191) dereferences a NULL pointer if a context is not available.

**Comment by rickyhan** [comment]
The only way get Context is https://docs.rs/imgui/0.1.0/imgui/struct.Ui.html#method.imgui

which is

> Deprecated since 0.1.0: This function is potentially unsafe and will be removed

**Comment by Gekkio** [comment]
If you have a `Ui` reference, you can use `Ui::frame_count`
