### ISSUE TITLE
error cargo run --example hello_world

### ISSUE THREAD

**Issue by letarg0** [imgui-rs/imgui-rs#256]
cargo run --example hello_world
warning: unused manifest key: badges.travis-ci.repository
warning: unused manifest key: package.categories
warning: unused manifest key: package.categories
warning: unused manifest key: package.edition
warning: unused manifest key: workspace.exclude
warning: unused manifest key: workspace.exclude
warning: unused manifest key: workspace.exclude
error: no example target named `hello_world`

linux arm

second trouble 'cc' library
cargo install cc

and next

cargo run --example hello_world
error: current package believes it's in a workspace when it's not:
current:   /home/itt/imgui-rs/imgui-examples/Cargo.toml
workspace: /home/itt/imgui-rs/Cargo.toml

this may be fixable by adding `imgui-examples` to the `workspace.members` array of the manifest located at: /home/itt/imgui-rs/Cargo.toml

**Comment by Gekkio** [comment]
What's the Rust version?

```
rustc --version
```

Note that imgui-rs requires at least 1.33

**Comment by dbr** [comment]
Closing old issue - sounds like problem was a too-old version of Rust toolchain
