### ISSUE TITLE
Example of creating a tree recursively

### ISSUE THREAD

**Issue by JoeHsiao** [imgui-rs/imgui-rs#261]
I am new to rust and imgui, and I am trying to create a tree by walking through a hierarchy recursively. Not sure if here is the right place to ask such question. Let me know if there is a better place. Below is me trying to build a tree recursively, but it's not 100% correct, and it can not compile due to a lifetime issue.

My question is am I going the right direction? Is there an example that I can follow?

```
struct TreeNode {
    name: String,
    children: Vec<TreeNode>,
}
impl Default for TreeNode {
    fn default() -> TreeNode {
        TreeNode {
            name: String::from("No Name"),
            children: Vec::new(),
        }
    }
}
fn create_tree() -> TreeNode {
    let mut node_1 = TreeNode {..Default::default()};
    let mut node_2 = TreeNode {..Default::default()};
    node_1.name = String::from("NODE 1");
    node_2.name = String::from("NODE 2");
    node_1.children.push(node_2);
    node_1
}
fn fill_node(_ui: &Ui, _node: &TreeNode) -> Box<Fn()->()> {
    if _node.children.len() == 0 {
        Box::new( move || {
            ui.tree_node(&im_str!("{}", _node.name)).build(|| {});
        })
    } else {
        Box::new( move || {
            _ui.tree_node(&im_str!("{}", _node.name)).build(||{});
            for t in _node.children {
                _ui.tree_node(&im_str!("{}", _node.name)).build(fill_node(_ui, &t));
            }
        })
    }
}

fn main() -> () {
    let root = create_tree();
    let system = support::init(file!());
    system.main_loop(|_, ui| {
        Window::new(im_str!("Tree View"))
            .size([300.0, 100.0], Condition::FirstUseEver)
            .build(ui, fill_node(ui, &root));
    });
}
```

**Comment by Jezza** [comment]
There's not a nested function tree node example, but that's closer to general Rust than it is to imgui.

If you're stuck with how to use the API, the `test_window_impl` example is pretty complete.
For example, the tree_node stuff is right [here](https://github.com/Gekkio/imgui-rs/blob/master/imgui-examples/examples/test_window_impl.rs#L356-L366).

Now, with regards to the nested function thing, it's possible:

```rust
struct Node {
	name: String,
	children: Vec<Node>
}

impl Node {
	fn new(name: impl Into<String>) -> Self {
		Node {
			name: name.into(),
			children: vec![],
		}
	}
}

fn fill_node(ui: &Ui, node: &Node) {
	ui.tree_node(&im_str!("{}", node.name))
		.build(|| {
			for child in &node.children {
				fill_node(ui, child);
			}
		});
}

let mut root = Node::new("First");
root.children.push(Node::new("First"));
root.children.push(Node::new("Second"));
root.children.push(Node::new("Third"));
root.children.push({
	let mut fourth = Node::new("Fourth");
	fourth.children.push(Node::new("First"));
	fourth.children.push(Node::new("Second"));
	fourth.children.push(Node::new("Third"));
	fourth
});

fill_node(ui, &root);
```

![Output](https://i.imgur.com/nYL0dWr.png)


I think the thing you were struggling with wasn't Rust itself, but rather how to build the `tree_node`s.
It's not the most straightforward, but generally, when imgui tries to build a component that requires a "close" or "end" function, imgui-rs will probably wrap a closure around it.
At least, that's what I've found.

As I said, the `test_window_impl` will probably help a lot.
I'd recommend you just run it, when you're building your UI, so you can look through the things you want, and see how it's done there.

Hope this was helpful.

**Comment by JoeHsiao** [comment]
Nice. Your code is much cleaner.

I have looked at the tree_node stuff in ```test_window_impl``` before, but I was disoriented with the usage of closure because I am still new to rust. I also like the way you define and use a struct.

**Comment by Jezza** [comment]
Haha, thanks.

Yeah, I can understand how it would be confusing, but the good news is, like everything else, it gets easier the more you do it.

Thanks!
My style probably isn't _perfect_ `rustfmt` style, but I like it a lot.

By the sounds of it, I've fixed your problem.
I'm glad I could help.
