### ISSUE TITLE
Can't build imgui with stable-x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by FrankvdStam** [imgui-rs/imgui-rs#263]
I've got this code:

```
extern crate glium;
extern crate imgui;
//use imgui::*;
use glium::{glutin, Surface};

fn main() 
{    
    let mut events_loop = glium::glutin::EventsLoop::new();
    let window_builder = glium::glutin::WindowBuilder::new();
    let context_builder = glium::glutin::ContextBuilder::new();
    let display = glium::Display::new(window_builder, context_builder, &events_loop).unwrap();
}
```

with these dependencies:
```
[dependencies]
glium = "*"
imgui = "*"
```

the line `extern crate imgui;` causes linker errors on the stable-x86_64-pc-windows-gnu toolchain.

Building with stable-x86_64-pc-windows-gnu

```
C:\projects\Thing>cargo build
   Compiling Thing v0.1.0 (C:\projects\Thing)

[irrelevant warnings]

    Finished dev [unoptimized + debuginfo] target(s) in 1.82s

C:\projects\Thing>cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s

C:\projects\Thing>cargo build
   Compiling Thing v0.1.0 (C:\projects\Thing)

[irrelevant warnings]

error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Users\\Frank\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\crt2.o" "C:\\Users\\Frank\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\Frank\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "\\deps\\libscopeguard-ea269b655c576354.rlib" "" "
[files] 

 "-Wl,--end-group" "C:\\Users\\Frank\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-b543334d3afc103d.rlib" "-Wl,-Bdynamic" "-lstdc++" "-ladvapi32" "-lopengl32" "-lwinapi_advapi32" "-lwinapi_cfgmgr32" "-lwinapi_comctl32" "-lwinapi_dwmapi" "-lwinapi_gdi32" "-lwinapi_kernel32" "-lwinapi_msimg32" "-lwinapi_ole32" "-lwinapi_opengl32" "-lwinapi_shcore" "-lwinapi_shell32" "-lwinapi_shlwapi" "-lwinapi_user32" "-lwinapi_uxtheme" "-lwinapi_winspool" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\Frank\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:\projects\Thing\target\debug\deps\libimgui_sys-2c93a82709b1c895.rlib(imgui.o): In function `ImGui::Shutdown(ImGuiContext*)':
          C:\Users\Frank\.cargo\registry\src\github.com-1ecc6299db9ec823\imgui-sys-0.2.0/third-party/cimgui/imgui/imgui.cpp:3954: undefined reference to `__imp___acrt_iob_func'
          C:\projects\Thing\target\debug\deps\libimgui_sys-2c93a82709b1c895.rlib(imgui.o): In function `ImGui::LogToTTY(int)':
          C:\Users\Frank\.cargo\registry\src\github.com-1ecc6299db9ec823\imgui-sys-0.2.0/third-party/cimgui/imgui/imgui.cpp:9166: undefined reference to `__imp___acrt_iob_func'


error: aborting due to previous error

error: Could not compile `Thing`.

To learn more, run the command again with --verbose.
```

switching to msvc:

```
C:\projects\Thing>rustup toolchain list
stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

C:\projects\Thing>rustup default stable-x86_64-pc-windows-msvc
info: using existing install for 'stable-x86_64-pc-windows-msvc'
info: default toolchain set to 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
```

Building with msvc:

```
C:\projects\Thing>cargo build

[cargo fetches and compiles stuff, bellow list seem the most relevant packages]

   Compiling imgui-sys v0.2.0
   Compiling glium v0.25.1
   Compiling winit v0.19.3
   Compiling imgui v0.2.1
   Compiling glutin v0.21.1
   Compiling Thing v0.1.0 (C:\projects\Thing)

[irrelevant warnings]

 Finished dev [unoptimized + debuginfo] target(s) in 21.46s

C:\projects\Thing>
```

I took a look at the file mentioned (C:\Users\Frank\.cargo\registry\src\github.com-1ecc6299db9ec823\imgui-sys-0.2.0/third-party/cimgui/imgui/imgui.cpp). Both unresolved references seem to have to do with stdout - both lines have it and there are no other references to stdout in the file (but I can't really imagine that being the only use of stdout in all of imgui).

I'm using msys64/mingw64 with rust 1.37 (`rustc 1.37.0 (eae3437df 2019-08-13)`), installed and updated last week on this machine, should be the latest version of everything. Does anyone need specific versions to help me? 

Since it works on windows, I'm probably at fault here. I've been trying to get specific versions of imgui and glium to play nice but no succes so far. I can't use the msvc toolchain because there's no debug support for msvc in Clion, thats why I use mingw.

Any ideas/suggestions?

**Comment by Gekkio** [comment]
As mentioned in the readme, mingw is not supported and only msvc is guaranteed to work. I think some people have had some success with mingw, but I don't have any idea if that required some changes to imgui-rs or not.

I'd *like* to support mingw but have already burned a huge amount of hours debugging problems with it. At least in the past only some very new mingw versions worked, and you had to make sure you installed the it with the correct calling convention that matches the mingw that Rust was built with.

If you do manage to get it to work, please report back. :sweat_smile:

**Comment by FrankvdStam** [comment]
Can't find anything about mingw in the readme. You spend hours debugging rust code or c++ code? I'm completely unfamiliar with rust-c++ bindings, imgui itself should run on mingw right?

**Comment by Gekkio** [comment]
> Note to Windows users: You will need to use the MSVC ABI version of the Rust compiler along with its associated dependencies to build this libary and run the examples.

:point_up: 

I think I should move that a bit higher in the readme since it's very important for Windows users.

> You spend hours debugging rust code or c++ code?

I've seen three different kinds of problems with mingw:

1. cimgui/imgui doesn't compile (https://github.com/Gekkio/imgui-rs/issues/1). So it fails already in C++ code
2. linking fails (either something about imm32, or this `__imp___acrt_iob_func` issue you're seeing now) (https://github.com/Gekkio/imgui-rs/issues/144, https://github.com/Gekkio/imgui-rs/issues/219)
3. crash at runtime (calling convention issues)

Since your issue is type 2, try checking those two linked issues if there's any hints how to make it work. Note that in both cases things started working with a different mingw version, but in one of the issues it was an *older version* and not the latest version so it seems very random to me. From my own experiments I know that you need to find a mingw version that is compatible with the mingw version that was used to build Rust, or else you will get type 2 or 3 problems.

**Comment by FrankvdStam** [comment]
Alright. In about a week or two I'll have some time, I'll see if I can figure anything out with the info you've just provided. Thanks and I'll let you know how things went.

**Comment by FrankvdStam** [comment]
Spent some time tonight, got this far:

1. Clone imgui-rs:
`C:\projects\nes\src\rustnes\lib\imgui-rs>git submodule update --init --recursive`

2. Build with mingw:
```
Frank@DESKTOP-3ISCQOT MINGW64 /c/projects/nes/src/rustnes/lib/imgui-rs/imgui-sys/third-party/cimgui
$ make
g++ -O2 -I./imgui/ -Wall -shared -c -o cimgui.o cimgui.cpp
g++ -O2 -I./imgui/ -Wall -shared -c -o imgui/imgui.o imgui/imgui.cpp
g++ -O2 -I./imgui/ -Wall -shared -c -o imgui/imgui_draw.o imgui/imgui_draw.cpp
g++ -O2 -I./imgui/ -Wall -shared -c -o imgui/imgui_demo.o imgui/imgui_demo.cpp
g++ -O2 -I./imgui/ -Wall -shared -c -o imgui/imgui_widgets.o imgui/imgui_widgets.cpp
g++ -o cimgui.dll cimgui.o ./imgui/imgui.o ./imgui/imgui_draw.o ./imgui/imgui_demo.o ./imgui/imgui_widgets.o -O2 -I./imgui/ -Wall -shared -limm32
Build complete for Windows
```

3. Run cargo build, make sure we're on the gnu toolchain

```
C:\projects\nes\src\rustnes\lib\imgui-rs>rustup default stable-x86_64-pc-windows-gnu
info: using existing install for 'stable-x86_64-pc-windows-gnu'
info: default toolchain set to 'stable-x86_64-pc-windows-gnu'

  stable-x86_64-pc-windows-gnu unchanged - rustc 1.38.0 (625451e37 2019-09-23)


C:\projects\nes\src\rustnes\lib\imgui-rs>cargo build
    Updating crates.io index
   Compiling semver-parser v0.7.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.8
   Compiling cc v1.0.45
   Compiling smallvec v0.6.10
   Compiling bitflags v1.2.0
   Compiling scopeguard v1.0.0
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling lock_api v0.3.1
   Compiling semver v0.9.0
   Compiling rustc_version v0.2.3
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling imgui-sys v0.3.0-pre (C:\projects\nes\src\rustnes\lib\imgui-rs\imgui-sys)
   Compiling imgui v0.3.0-pre (C:\projects\nes\src\rustnes\lib\imgui-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 14.89s
```

4. Change dependency in main project (cargo.toml):

```
#imgui = "0.2.0"
imgui = { path = "lib/imgui-rs" }
```

5. Get compiler errors when building the main project -> default imgui-rs branch is master. Lets go back to 0.2.x

```
C:\projects\nes\src\rustnes\lib\imgui-rs>git branch
* master

C:\projects\nes\src\rustnes\lib\imgui-rs>git checkout release/0.2.x
Switched to a new branch 'release/0.2.x'
M       imgui-sys/third-party/cimgui
Branch 'release/0.2.x' set up to track remote branch 'release/0.2.x' from 'origin'.
```

6. Rerun make via mingw and cargo build imgui-rs

7. Realize I have more dependencies

```
#imgui-glium-renderer = "0.2.0"
#imgui-winit-support = "0.2.0"

imgui-glium-renderer = { path = "lib/imgui-rs/imgui-glium-renderer" }
imgui-winit-support = { path = "lib/imgui-rs/imgui-winit-support" }
```

8. Square 1, back to the linker errors

```
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" " [loads of files]
  = note: C:\projects\nes\src\rustnes\target\debug\deps\libimgui_sys-99b114c8f617feec.rlib(imgui.o): In function `ImGui::Shutdown(ImGuiContext*)':
          C:\projects\nes\src\rustnes\lib\imgui-rs\imgui-sys/third-party/cimgui/imgui/imgui.cpp:4000: undefined reference to `__imp___acrt_iob_func'
          C:\projects\nes\src\rustnes\target\debug\deps\libimgui_sys-99b114c8f617feec.rlib(imgui.o): In function `ImGui::LogToTTY(int)':
          C:\projects\nes\src\rustnes\lib\imgui-rs\imgui-sys/third-party/cimgui/imgui/imgui.cpp:9266: undefined reference to `__imp___acrt_iob_func'
```
		  
9. Remove references to stdout in imgui.cpp:4000 and imgui.cpp:9266 by commenting the whole if statement -> code builds and runs but crashes after a couple of seconds: `error: process didn't exit successfully: target\debug\abaraad.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`


So I fixed the linker errors, got a runtime error in return. stdout is defined in iostream, adding

`#include <iostream>`

Didn't cut it. That's it for tonight, more later.

**Comment by FrankvdStam** [comment]
Just tried WSL, same linker errors as on mingw (I'm not sure I set it up right). It does build when I copy the files over and build there via command line, obviously it doesn't run since there is no backend.

Is there any information about building issues with WSL?

**Comment by a1ien** [comment]
I think we can close this issues it's related to https://github.com/rust-lang/rust/issues/47048 and on last version rust fixed.

**Comment by sanbox-irl** [comment]
is it @FrankvdStam ?

**Comment by FrankvdStam** [comment]
I guess technically mingw was never supported anyway. I don't use this anymore so feel free to close it. If at all relevant I can try (sometime this week? Month?) to compile and see if it works now, let me know.

**Comment by sanbox-irl** [comment]
No pressure. I will close and if you feel a powerful urge to help, I'd appreciate it, but i'm alright with the lib as it is
