### ISSUE TITLE
Modal Popups

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#265]
Hi -- is there any plans of tackling modal popups for the changes that were seen in the 0.2 change? I've really enjoyed not having to work with closures, and I'd like to transition my modal popups too.

Very willing to help! Seems relatively straightforward -- just a few extra functions in the modal popup.

**Comment by Gekkio** [comment]
Yeah, all popups and trees are currently getting an overhaul for 0.3.0. I might push something to master later this week

**Comment by sanboxrunner** [comment]
thanks bud, appreciate all the work you do. Is there a tracking issue for 0.3 buried somewhere?

**Comment by Gekkio** [comment]
There is now :smile:

https://github.com/Gekkio/imgui-rs/issues/267

**Comment by rasky** [comment]
Currently, there's no way to set the size of a popup. It looks like I need to call the low-level igSetNextWindowSize. Probably, ModalPopup should grow a size method like other windows.

**Comment by sanbox-irl** [comment]
ah this is done. closing
