### ISSUE TITLE
Support for input callbacks

### ISSUE THREAD

**Issue by ondrowan** [imgui-rs/imgui-rs#272]
Is there any way to invoke callbacks in inputs? Eg. `CallbackAlways` or `CallbackCharFilter`. I noticed you can set flags for them, but I can't find any way to actually pass them to inputs.

**Comment by vityafx** [comment]
I also have no idea how to get notified when, for example, in a `TextInput` widget we've pressed "Enter", so I can't process the text written there.

**Comment by pferreir** [comment]
Also wondering that.

**Comment by dbr** [comment]
Done in https://github.com/imgui-rs/imgui-rs/pull/516
