### ISSUE TITLE
Frame limit

### ISSUE THREAD

**Issue by AndreaCatania** [imgui-rs/imgui-rs#278]
By running both the examples (Glium and gfx) I noticed that the frame rate is capped to 120
```
[examples/hello_world.rs:18] ui.io().framerate = 118.971596
[examples/hello_world.rs:18] ui.io().framerate = 119.00258
[examples/hello_world.rs:18] ui.io().framerate = 118.98891
[examples/hello_world.rs:18] ui.io().framerate = 118.98866
```
I've already removed the VSync (even if I've a 144hz monitor, so 120 is not due to VSync) but nothing change.
After some tests, I'm able to say that the frame limit is set in Glium, and I'm pretty sure that it depends on some internal configuration of the render.

I would like to remove this frame cap, because I would like to fully use the VSync, any idea?

**Comment by dbr** [comment]
Closing old ticket

The ~120fps cap is very odd - not sure what might have caused this. With the current imgui-glium-renderer examples, if I change

```
index af26bc2..83e95ee 100644
--- a/imgui-examples/examples/support/mod.rs
+++ b/imgui-examples/examples/support/mod.rs
@@ -26,7 +26,7 @@ pub fn init(title: &str) -> System {
         None => title,
     };
     let event_loop = EventLoop::new();
-    let context = glutin::ContextBuilder::new().with_vsync(true);
+    let context = glutin::ContextBuilder::new().with_vsync(false);
```

Then the frame-rate becomes uncapped:
![image](https://user-images.githubusercontent.com/509/149848325-239758d9-2eea-4f30-9e8e-d5e6e2fe6931.png)
