### ISSUE TITLE
Windows 10: Hide encompassing window

### ISSUE THREAD

**Issue by pyroxymat** [imgui-rs/imgui-rs#299]
So I running the example in Windows 10 (built myself). But I get my Windows screen wherein the IMGUI window is located. Is it possible to only get the IMGUI screen without the windows screen around it? Here is a picture of what I see:

![image](https://user-images.githubusercontent.com/3037921/74447286-67efce80-4e79-11ea-85fd-c24d8bff06b1.png)

**Comment by sanbox-irl** [comment]
Yes. Sort of.

Assuming you're using Winit, maximize the size of your ImGui window to the size of your winit window. When you create your winit window, pass in `.with_decorations(false)` to the builder, and it will not show you the outer frame.

The outer frame *still exists* of course -- just you won't see it.

It's worth pointing out here though that ImGui isn't really for end users -- it's meant for developers. I wouldn't ship it as your UI

**Comment by naiba** [comment]
![image](https://user-images.githubusercontent.com/29243953/159122783-d83a5419-d4d7-4e0d-9a04-0630e64fe896.png)

![image](https://user-images.githubusercontent.com/29243953/159122794-28dc41d6-6467-4194-bc01-ff7796d6eb40.png)

@sanbox-irl Can we hide the white background?
