### ISSUE TITLE
hello_world example scales incorrectly on osx

### ISSUE THREAD

**Issue by woelper** [imgui-rs/imgui-rs#314]
I noticed that scaling the window causes its contents to be scaled incorrectly on Mac Os X (Catalina/10.15.3).
The screenshot is from `imgui-gfx-examples/examples/hello_world.rs`. The window has been resized horizontally.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/3613791/79376463-81d18e80-7f5a-11ea-9fad-2bbf495472d3.png">

**Comment by dbr** [comment]
Closing old issue - the old `gfx` backend is long deprecated, and I'm not aware of any issues on macOS with the current backends/renderers
