### ISSUE TITLE
Modifier keys always false on winit + mac

### ISSUE THREAD

**Issue by emilk** [imgui-rs/imgui-rs#329]
On `master`, on Mac Catalina.

Reproduce: in `imgui-gfx-examples/examples/hello_world.rs`, add:

``` rust
ui.text(format!("key_shift: {}", ui.io().key_shift));
ui.text(format!("key_ctrl: {}", ui.io().key_ctrl));
ui.text(format!("key_alt: {}", ui.io().key_alt));
ui.text(format!("key_super: {}", ui.io().key_super));
```

Run `cargo run --example hello_world` and press modifier keys. They all remain false.

A short investigation of `imgui-winit-support/src/lib.rs` shows that I do get `WindowEvent::KeyboardInput` in

``` rust
    #[cfg(feature = "winit-19")]
    fn handle_window_event(&mut self, io: &mut Io, window: &Window, event: &WindowEvent) {
        ...
    }
```

Maybe the modifier keys should be updated [there](https://github.com/Gekkio/imgui-rs/blob/master/imgui-winit-support/src/lib.rs#L494)

**Comment by Gekkio** [comment]
Sounds like a potential regression originating from this commit: https://github.com/Gekkio/imgui-rs/commit/2f57a3099a2778e877f05e2463aeaeef5976f564

**Comment by Gekkio** [comment]
I don't have a Mac myself, so I'm afraid the only thing I can do is merge reasonable-looking pull requests :shrug: 

If you have the time and a machine to debug this, try reverting the winit 0.19 changes from the commit I linked. I suspect it was maybe only tested on winit 0.20+, so winit 0.19 code shouldn't have been changed at all.

**Comment by dbr** [comment]
Closing; modifiers on macOS definitely work with more recent winit+imgui-rs versions, and winit 0.19 is almost 2 years old at this point so unlikely to be used by anyone on new projects
