### ISSUE TITLE
Cannot abstract out window contents, Ui is borrowed by build()

### ISSUE THREAD

**Issue by cosmicchipsocket** [imgui-rs/imgui-rs#332]
So here's a conundrum. I am currently working on an editor for my game engine. At this point I am trying to create document windows for different types of assets. I have a Document trait with a function taking an &mut Ui, so that it can specify what the document window contents should be. Unfortunately, this does not play nice with Rust's borrowing rules:

```rust
imgui::Window::new(&im_str!("{}", document.window_name())).focused(raise).opened(&mut window_open).position([320.0, 48.0], imgui::Condition::Appearing)
    .size([640.0, 640.0], imgui::Condition::Appearing).build(ui, ||
{
    document.do_ui(editor, ui);
});
```

```
error[E0500]: closure requires unique access to `ui` but it is already borrowed
    |
420 |     .size([640.0, 640.0], imgui::Condition::Appearing).build(ui, ||
    |                                                        ----- --  ^^ closure construction occurs here
    |                                                        |     |
    |                                                        |     borrow occurs here
    |                                                        first borrow later used by call
421 | {
422 |     document.do_ui(editor, ui);
    |                            -- second borrow occurs due to use of `ui` in closure
```

Is there any way to solve this?

**Comment by cosmicchipsocket** [comment]
Found a workaround: pass a Window builder object with some pre-set properties into the function, along with the Ui, so that the window is built inside the function where the Ui borrow isn't subject to the function barriers that the borrow checker seems to dislike so much.

**Comment by Gekkio** [comment]
Does it help if you use `begin`+`end` instead of `build`?

**Comment by cosmicchipsocket** [comment]
A bit late on this, but I did some recent refactoring to move to a tabbed interface and I started using the begin/end API. So far it's worked very well for me. I have noticed however that CollapsingHeader does not have begin/end. Created #481 for this.
