### ISSUE TITLE
input_text(&self,ImStr,&mut ImString)  behaves weird and buggy in any sort of loop.

### ISSUE THREAD

**Issue by einmensch** [imgui-rs/imgui-rs#340]
im trying to make a window displaying a .csv table and for some reason every attempt at rendering the` Vec<Vec<ImString>> `results in it beign rendered correctly but every time i select a cell it breifly flashes, copies its content to the next cell in the table and unselects itself. this happens even if i pass the same &mut ImString to all cells, i think i at some point managed to input a single character in the brief moment the cell is selected.

my current implementation of rendering the table:
```
 for i in 0..self.table.len()-1 {
    ui.new_line();
    for j in 0..self.table[i].len()-1 {
         ui.input_text(im_str!(""),&mut self.table[i][j]).build();
         ui.same_line_with_spacing(0.,1.);
     }
 }
```

**Comment by Gekkio** [comment]
Please read the [upstream FAQ about ID stacks](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-are-multiple-widgets-reacting-when-i-interact-with-one). To me it looks like you're creating multiple conflicting text input widgets with the `""` label (which happens to be the ID as well for text inputs)
