### ISSUE TITLE
Gap between window and imgui window in i3 window manager

### ISSUE THREAD

**Issue by azzamsa** [imgui-rs/imgui-rs#360]
Step to reproduce:

1. `cd imgui-gfx-examples`
2. `cargo run --example test_window`

![image](https://user-images.githubusercontent.com/17734314/92541555-92b7cf00-f270-11ea-99e9-20af6fdc0db8.png)

Info:
``` 
$ rustc -V
rustc 1.45.1 (c367798cf 2020-07-26)

OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-5-amd64
WM: i3
GPU: Intel UHD Graphics 620
```

---

I don't know it this happens with `imgui` directly. I've tried to clone their repo, but having difficulties to run the examples.

Fyi, this problem also happens in other (non-rust) [project](https://github.com/akiraux/Akira/issues/3#issuecomment-675820565)

**Comment by sanbox-irl** [comment]
Can you give more information on what you mean by "gap"? The small `dear imgui window` there is re-positionable, so you should be able to make it around however you'd like.

**Comment by azzamsa** [comment]
the white-space between the imgui window and the i3 window border.

**Comment by sanbox-irl** [comment]
The internal imgui window isn't meant to aligned to the Operating System provided window. It's movable

**Comment by thomcc** [comment]
> the white-space between the imgui window and the i3 window border.

ImGUI windows aren't real OS windows. They're windows drawn *inside* a real OS window (the thing with the white space in your screenshot). And so we can't follow the behavior of your window manager, nor would it be sensible to try.

It sounds like you're probably looking for a more fully-featured/OS-native UI solution than ImGUI offers.

**Comment by azzamsa** [comment]
I want to record it with `peek` to give more illustration of the white-space between window-manager window and imgui. But I can't compile a new revision, even if I try a couple of times.

```
  = note: collect2: fatal error: ld terminated with signal 11 [Segmentation fault]
          compilation terminated.
```

**Comment by thomcc** [comment]
That doesn't sound like our bug (it sounds like a bug in your linker).

But, I am pretty sure I can see the white space, and I understand what you're complaining about, but it's by design, and not really a bug with ImGui...

**Comment by azzamsa** [comment]
Yes, this also happening in other apps: [akira app](https://github.com/akiraux/Akira/issues/3#issuecomment-675820565)

> It sounds like you're probably looking for a more fully-featured/OS-native UI solution than ImGUI offers.

Reading [this comment](https://github.com/akiraux/Akira/issues/3#issuecomment-691446176), I think the issue only happens in i3wm. Maybe the only solution is to use another window manager of full Desktop Environment such as GNOME/KDE.

Thanks for the help
