### ISSUE TITLE
Linking against custom Dear Imgui version

### ISSUE THREAD

**Issue by greaka** [imgui-rs/imgui-rs#370]
Hi there,

I would like to use a specific Dear Imgui version to link against. I am getting the imgui context via C FFI and dont need to provide a backend or renderer. Is it possible for me to fork this project and get it to run the specific version? What steps do I need to take?

**Comment by sanbox-irl** [comment]
@greaka more or less, those steps have been written out here (sorry for the delay in response). We're hoping to automate more and more of this process so a custom imgui fork would have an easier time: https://github.com/imgui-rs/imgui-rs/issues/435

**Comment by greaka** [comment]
Hey there,
I pressured my dependency into updating the imgui version by now. Thanks for the response though 🙂
