### ISSUE TITLE
Am I able to build complete full Android apps?

### ISSUE THREAD

**Issue by Joe23232** [imgui-rs/imgui-rs#373]
Hi I have a few questions regarding this project.

1. Am I able to build complete full Android apps?
2. Is this a complete replacement of using Android Studio with Java?
3. Is it cross compatible between iOS and Android?

**Comment by alula** [comment]
1. It does work on Android, but the winit backend doesn't have any support for touch yet. It's also not really suitable for proper mobile apps, maybe as a little debugging overlay UI.
2. cargo-apk is what you're looking for
3. depends on your dependencies

**Comment by thomcc** [comment]
@alula's answers are relatively accurate (thanks).

1. Not with this crate alone.
2. No.
3. This code is, but your dependencies may not be.

Hopefully this answers your questions.
