### ISSUE TITLE
Which `key_index` to pass to `is_key_pressed` with glutin backend?

### ISSUE THREAD

**Issue by Boscop** [imgui-rs/imgui-rs#377]
Which `key_index` to pass to `is_key_pressed` with glutin backend?

`is_key_pressed` calls `IsKeyPressed`:
```
    // Inputs Utilities: Keyboard
    // - For 'int user_key_index' you can use your own indices/enums according to how your backend/engine stored them in io.KeysDown[].
    // - We don't know the meaning of those value. You can use GetKeyIndex() to map a ImGuiKey_ value into the user index.
    IMGUI_API int           GetKeyIndex(ImGuiKey imgui_key);                                    // map ImGuiKey_* values into user's key index. == io.KeyMap[key]
IMGUI_API bool          IsKeyPressed(int user_key_index, bool repeat = true);               // was key pressed (went from !Down to Down)? if repeat=true, uses io.KeyRepeatDelay / KeyRepeatRate
```

I want to check for certain key combos while certain widgets are focused. 
E.g. pressing Enter on a table cell that is a text should turn it into an edit field, and `Ctrl+Enter` in a `input_text_multiline` should "submit" it etc.
Checking glutin's events directly doesn't scale for my use case, I need to check them at the point where I render each widget, that's why I need `is_key_pressed`. (Btw, I already have the `ModifiersState`, I just need to figure out how to make `is_key_pressed` work for normal keys like Enter.)

---

Btw, is there already a way to "submit" a `input_text_multiline`, similar to  `.enter_returns_true(true)` for `input_text`? When does `InputTextMultiline::build()` return `true`?

**Comment by Boscop** [comment]
Ah, I had assumed I need to somehow figure out the scancode for each of Glutin's keys and convert it to imgui's codes, but I figured out this works:
```rust
	if self.modifiers == ModifiersState::CTRL
		&& ui.is_key_pressed(ui.key_index(Key::Enter))
	{
		println!("Ctrl+Enter pressed");
	}
```

But why does [`Key`](https://docs.rs/imgui/0.4.0/imgui/enum.Key.html) only have so few of the available keyboard keys?

---

I want to respond to Ctrl+Enter only while the cursor is active in the `input_text_multiline`.
But this doesn't work:
```rust
	let res = ui
		.input_text_multiline(
			im_str!("##multiline"),
			&mut self.input_arr_pattern_expr,
			[300., 100.],
		)
		.build();
	if res {
		println!("{:?}", (r, ui.is_item_focused()));
	}
```
`is_item_focused()` ALWAYS returns `false`. Why?

**Comment by dbr** [comment]
> But why does Key only have so few of the available keyboard keys?

In the upstream C++ library, the key enum currently only contains the few keys it actually uses directly (for operations like copy/paste, selecting all, etc) for various reasons - although if https://github.com/ocornut/imgui/pull/2625 gets merged it will increase the number of keys significantly

> Ah, I had assumed I need to somehow figure out the scancode for each of Glutin's keys and convert it to imgui's codes, but I figured out this works:

For keys outside of the `imgui::Key` enum that's what you have to do - note the API for this disappeared in 0.7.0 but should be back for 0.8.0; for details see https://github.com/imgui-rs/imgui-rs/issues/455 and relating PR https://github.com/imgui-rs/imgui-rs/pull/463

> Because as soon as I press Ctrl+Enter, imgui apparently unfocuses the input for some reason, so is_item_active() returns false! How can I prevent this unfocusing?

I think ctrl+enter causing the widget to lose focus is default functionality of the multi-line input:

https://github.com/ocornut/imgui/blob/a1a39c632aaf2a1ab7fe09961748a2f25816fb6e/imgui.h#L947
> `ImGuiInputTextFlags_CtrlEnterForNewLine = 1 << 11,  // In multi-line mode, unfocus with Enter, add new line with Ctrl+Enter (default is opposite: unfocus with Ctrl+Enter, add line with Enter).`

I'm not sure if there is a "good" way to disable this functionality if you want to do something custom with ctrl+enter, but you could possibly set the `CtrlEnterForNewLine` flag if ctrl is pressed to circumvent the behaviour - but that is pretty hacky and might do undesirable things when the enter key being passed.

**Comment by dbr** [comment]
This will be significantly reworked in imgui 1.87 and should simplify things (making the key handling consistent across backends):

https://github.com/ocornut/imgui/issues/4858

Shall close this issue as updates to the new API will happen via a future PR
