### ISSUE TITLE
Question about Icons

### ISSUE THREAD

**Issue by Boscop** [imgui-rs/imgui-rs#378]
I would like to have toolbar icons like in this UI:

[![image](https://user-images.githubusercontent.com/535593/96080249-f1e3b180-0eb6-11eb-8379-87127fdfbd22.png)](https://www.youtube.com/watch?v=1tgPnYAhyhc)

Do I just need to port the CPP headers? https://github.com/juliettef/IconFontCppHeaders
https://github.com/ocornut/imgui/blob/e610afeea31a8e8f659b2762591444e19fad55c1/misc/fonts/README.txt#L44-L84

How do I add it to my main font that I'm already using with imgui?

And how can I make them big like in that screenshot? (Bigger than normal font size.)

**Comment by dbr** [comment]
*Slightly* belated reply, but in case it's of use to anyone still

We use something like https://docs.rs/material-icons/latest/material_icons/ as a Rust'y equivelant to the IconFontCppHeaders (it's basically identical to this crate except I made`Icon` implement `Display`, so it works to just do `format!("{} Thing", Icon::Whatever)`, and I also added a `GLYPH_RANGE` constant)

> And how can I make them big like in that screenshot? (Bigger than normal font size.)

The simplest thing might be just to load the icons from a `.png` file or similar (although setting up the texture loading isn't the simplest thing to do)

With a font based icon set:

You can force the font size to bigger with something like `set_window_font_scaling` or similar, but it just bilinearly upscales the font texture which typically looks pretty soft

It's probably best to add your icon-font as a secondary font with a larger font size,

    let main_font_id = imgui_context.fonts().add_font(&[
        ...
    ]);

    let big_icon_font = imgui_context.fonts().add_font(&[
        imgui::FontSource::TtfData {
            data: material_icons::FONT,
            size_pixels: font_size * 2.0,
            config: Some(FontConfig {
                glyph_ranges: imgui::FontGlyphRanges::from_slice(&material_icons::GLYPH_RANGE),
                ..FontConfig::default()
            }),
        },
    ]);

Then to use it you do something like:

    let font_override = ui.push_font(big_icon_font)
    ui.text(format!("{}", icon_to_char(Icon::Rotation3d)))
    font_override.end()
