### ISSUE TITLE
Auto-resizable multiline input

### ISSUE THREAD

**Issue by Boscop** [imgui-rs/imgui-rs#380]
I want to use `input_text_multiline` for a code editor but it only works if I init its string like `ImString::with_capacity(1000)`.

1. I don't want to limit it. How can I make it grow automatically or at least get notified when it's reached its limit so that I can manually enlarge it?
2. Is there any way to get the current cursor char position inside an `input_text` or `input_text_multiline`?
3. Is there any way to do syntax highlighting or at least paren matching/highlighting?

**Comment by DGriffin91** [comment]
I can't speak to the other questions here, but you may want to look at the Text Editors section of the Dear IMGUI wiki: https://github.com/ocornut/imgui/wiki

You may be able to wrap one of those other implementations to be used from imgui-rs, or at least see how they went about implementing various features you may need.

**Comment by db48x** [comment]
ImString is already growable. The with_capacity method simply creates an empty ImString with an initial capacity of 1000.

https://docs.rs/imgui/0.6.0/imgui/struct.ImString.html

**Comment by thomcc** [comment]
Thanks for responding (I really need to go through this issue backlog...). What @db48x said is correct.

**Comment by benmkw** [comment]
This is not really a great way to make Input robust as you need an upper bound on the user input size and/ or be very cautious and overallocate (and still possibly fail). I think the only way one might get around this currently is by reacting to each key press and resizing on demand although I’m not sure how this works for copy paste.

When I ran into this issue I just overallocated and did not look into it much further, maybe I’m missing something.

**Comment by thomcc** [comment]
Hmm, I see, the issue description is a bit bad so I misunderstood. This is more about how we call the multiline input API.

**Comment by DGriffin91** [comment]
I think you can use `.resize_buffer(true)` before building and it will resize as needed.

I made an example below. You can see the capacity go up as you enter stuff. Pasting works fine. I pasted in 20 million characters and it seemed to handle it fine.

```rust
use imgui::*;
mod support;
fn main() {
    let mut text = ImString::new("");
    let system = support::init(file!());
    system.main_loop(move |_, ui| {
        Window::new(im_str!("Hello world"))
            .size([400.0, 400.0], Condition::FirstUseEver)
            .build(ui, || {
                ui.label_text(
                    im_str!("Capacity"),
                    &ImString::new(format!("{}", text.capacity())),
                );
                ui.input_text_multiline(im_str!("##text"), &mut text, [300.0, 300.0])
                    .resize_buffer(true)
                    .build();
            });
    });
}

```

If anyone knows a better (shorter?) way to do `ImString::new(format!("{}", text.capacity()))` for the label, let me know haha.

**Comment by thomcc** [comment]
Ah, this is all telling me that I need to spend more than a few minutes
looking into this (in my defense, it’s very late and I’m on vacation). I’ll
investigate more later, but that sounds right. Possibly should be the
default behavior. Thanks

**Comment by DGriffin91** [comment]
I'm not sure if anyone would be currently depending on it _not_ being the default behavior? I'm also not sure where this project is at currently on API stability. It could make sense if something like this is changed to highlight it in the changelog for the release so people can know to look for breaking changes. Obviously this is a pretty minor item, but I could see it being an issue if someone was expecting their ImString size to not be affected by a multiline text.

Have a good vacation :) Please don't feel like you can't take a break from working.

**Comment by sanbox-irl** [comment]
Hey all -- we talked this over briefly, and I think the current plan is the following:
first, `resize_buffer(true)` will be made default. It's not very Rust-y for it to not be, especially with the `ImString` song and dance we have to do.

Secondly, in the future, these inputs will get some rewrites to be simpler and nice to use (though this may end up being somewhat breaking) -- if you have any thoughts on that, drop em here https://github.com/imgui-rs/imgui-rs/issues/430.

I'll update this issue when I get around to pushing the change to the resizable buffer (tomorrow probably), which will hopefully be in time for the 0.7 release

**Comment by dbr** [comment]
With the rework for the text-input callbacks, I'm pretty sure this is now the default behaviour - possibly even the only currently available behaviour as `do_not_resize` is commented out, and there's not been huge(/any) complaints so far:

https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui/src/input_widget.rs#L384-L398
