### ISSUE TITLE
drag_float3 removed

### ISSUE THREAD

**Issue by aentity** [imgui-rs/imgui-rs#382]
It seems drag_float3 removed in 0.5. I do not see in changelog this removal, and do not see what to replace with.

Drag array is not same as drag float3. Am I missing it?

**Comment by Gekkio** [comment]
> I do not see in changelog this removal

"Redesigned drag slider API" means everything involving drag sliders was changed, and this includes `drag_float3`.

> Drag array is not same as drag float3

Can you elaborate a bit? In the upstream C++ code, `DragFloat3` is implemented using `DragScalarN`, which is what almost all drags use now behind the scenes in imgui-rs.
Doesn't something like this work?

```rust
let mut some_data: [f32; 3] = ...
Drag::new(im_str!("Some floats")).build_array(&ui, &mut some_data);
```

**Comment by sanbox-irl** [comment]
Going to close this issue since I think it's been made clear where drag_float3 ended up! Let me know if I should open it up again.

Thanks for submitting an issue!
