### ISSUE TITLE
missing imgui_internal bindings

### ISSUE THREAD

**Issue by dneumair** [imgui-rs/imgui-rs#395]
Hi there!

first of all i want to tell you, i am grateful that you are willing to maintain this repo.

the imgui-sys bindings are missing the functions from imgui_internal.h This was probably by choice, because in the cimgui.h file from the cimgui repo includes them. (i think you can choose with the lua generator script, if you want to include the internals)

For the standard usecase this is sufficent but if someone wants to create advanced widgets like the nodeeditor [https://github.com/thedmd/imgui-node-editor](url) you are running into a brick wall.

Furthermore i familiarized myself with the bindgen tool and got the plain imgui c++ bindings working. (Currently working on compiling the cpp-codebase with cmake and linking rust against it)
This would make it possibile to leave out cimgui all together and use imgui directly. (one indirection less ... yay! :) )

Also If you want me to, i would be happy to participating in maintaining this repo.

**Comment by thomcc** [comment]
Seems reasonable and I already have some plans for the -sys crate. Will look into it this evening.

**Comment by dneumair** [comment]
got it up and running now...
yes the sys crate is a little bit inconsistent with the bindgen-sys and the imgui-sys

**Comment by norcalli** [comment]
I, too, am running into this very often. I understand that the imgui safe bindings may be behind sometimes, but an escape hatch is needed, otherwise you may hit a roadblock that is either impossible to surmount or takes many hours to do so. If this could be prioritized to make usability higher before undertaking more time consuming refactors (while those may seem fun and exciting to a new maintainer), I would appreciate it @thomcc

**Comment by 4bb4** [comment]
I'd also be interested in having the internal bindings - I maintain https://github.com/4bb4/implot-rs, which points to https://github.com/cimgui/cimplot, and the latter exposes the internal API and hence requires cimgui to also expose the internal API. My code actually uses the cimgui that is vendored in the repo here (via the `DEP_IMGUI_THIRD_PARTY` environment variable) to make sure `implot-rs` plays nicely with `imgui-rs`.

I'd be happy to contribute some work towards this if desired.

**Comment by HactarCE** [comment]
> got it up and running now...

Do you mean that you have a fork with working `imgui_internals.h` bindings?
