### ISSUE TITLE
imgui-winit-support crate uses reversed cursor as default on Linux

### ISSUE THREAD

**Issue by noxabellus** [imgui-rs/imgui-rs#409]
**Describe the bug**
The default cursor is backwards on Linux.

**To Reproduce**
Run any example code utilizing imgui-winit-support, on Linux.

**Expected behavior**
Expected cursor to point left, not right.

**Screenshots**
The cursor should look like this:
![proper_cursor](https://user-images.githubusercontent.com/13547335/102702207-c4541500-4225-11eb-910d-dc1ad41293b3.png)

Instead, it looks like this:
![backward_cursor](https://user-images.githubusercontent.com/13547335/102702209-c8803280-4225-11eb-83de-c3dfe1c65753.png)

**Please describe your environment**
 - imgui-rs version is 0.6
 - Operating system version:
 ```
   Operating System: Pop!_OS 20.04 LTS
   Kernel: Linux 5.8.0-7630-generic
   Architecture: x86-64
```

**Other information**
This is caused by [the following line](https://github.com/imgui-rs/imgui-rs/blob/master/imgui-winit-support/src/lib.rs#L288):
```rust
imgui::MouseCursor::Arrow => MouseCursor::Arrow,
```
The winit docs here are misleading, Arrow is not precisely "self-explanatory."

**Comment by thomcc** [comment]
Hm, I'm away so can't do much more than click a "merge" button, but patches are very welcome to improve experience on different OSes

**Comment by noxabellus** [comment]
I've made a [PR to fix this](https://github.com/imgui-rs/imgui-rs/pull/410)
