### ISSUE TITLE
Problem with get_background_draw_list()

### ISSUE THREAD

**Issue by nsf** [imgui-rs/imgui-rs#413]
**Describe the bug**
If one uses ui.get_background_draw_list() outside of the window context, a new window is being created with "Debug" title.

**To Reproduce**
I modified the "hello_world" example with this code, note that it should draw a thick line across the screen, but additional window is being created:
```rust
use imgui::*;

mod support;

fn main() {
    let system = support::init(file!());
    system.main_loop(move |_, ui| {
        let dl = ui.get_background_draw_list();
        dl.add_line([0.0, 0.0], [640.0, 480.0], [1.0, 0.0, 0.0])
            .thickness(5.0)
            .build();

        Window::new(im_str!("Hello world"))
            .size([300.0, 110.0], Condition::FirstUseEver)
            .build(ui, || {
                ui.text(im_str!("Hello world!"));
                ui.text(im_str!("こんにちは世界！"));
                ui.text(im_str!("This...is...imgui-rs!"));
                ui.separator();
                let mouse_pos = ui.io().mouse_pos;
                ui.text(format!(
                    "Mouse Position: ({:.1},{:.1})",
                    mouse_pos[0], mouse_pos[1]
                ));
            });
    });
}
```

**Expected behavior**
It should not create any additional windows when using drawlists.

**Screenshots**
![image](https://user-images.githubusercontent.com/12567/103173213-2262a700-487b-11eb-90e4-6925fd771d0c.png)

**Please describe your environment**
I tried it on "master" right now, but it's valid for 0.6.1 as well. OS is irrelevant, but it's linux.

**Other information**
Quick glance at the source code shows this:
https://github.com/imgui-rs/imgui-rs/blob/eada611c2ce822054596833c8edb3122e77ee7db/imgui/src/lib.rs#L490-L493

And this:
https://github.com/imgui-rs/imgui-rs/blob/eada611c2ce822054596833c8edb3122e77ee7db/imgui/src/window_draw_list.rs#L87

My guess is that because igGetWindowDrawList() is called for background draw list as well, it causes window to be revealed in imgui when used outside of the window context. Quick glance at imgui's source code indeed confirms this, they always have "Debug" window in the stack:
https://github.com/ocornut/imgui/blob/fa963b9aafde7f05b1d32d42e3d2b084c9685e31/imgui_internal.h#L2140

Most likely avoiding the call to igGetWindowDrawList() will fix this. I.e. this sould be a "static method": 
https://github.com/imgui-rs/imgui-rs/blob/eada611c2ce822054596833c8edb3122e77ee7db/imgui/src/window_draw_list.rs#L92

**Comment by thomcc** [comment]
Hmm. I think the reason it's not a static method is also for thread-safety reasons.

That said, I can look more later, perhaps you're right.

**Comment by nsf** [comment]
Well, I can see that WindowDrawList interacts with static atomic bool WINDOW_DRAW_LIST_LOADED, that's true. It "locks" it on creation and "unlocks" it on drop(). But you don't have to call igGetWindowDrawList to capture it. You can probably refactor it to something like this:
```rust
impl<'ui> WindowDrawList<'ui> {
    fn lock_draw_list() {
        let already_loaded = WINDOW_DRAW_LIST_LOADED
            .compare_exchange(
                false,
                true,
                std::sync::atomic::Ordering::Acquire,
                std::sync::atomic::Ordering::Relaxed,
            )
            .is_err();
        if already_loaded {
            panic!("WindowDrawList is already loaded! You can only load one instance of it!")
        }
    }
    
    pub(crate) fn new(_: &Ui<'ui>) -> Self {
        Self::lock_draw_list();
        Self {
            draw_list: unsafe { sys::igGetWindowDrawList() },
            _phantom: PhantomData,
        }
    }

    pub(crate) fn background(_: &Ui<'ui>) -> Self {
        Self::lock_draw_list();
        Self {
            draw_list: unsafe { sys::igGetBackgroundDrawList() },
            _phantom: PhantomData,
        }
    }
}
```

Maybe worth renaming WINDOW_DRAW_LIST_LOADED -> DRAW_LIST_LOADED too and WindowDrawList -> DrawList. As it's not just about a window draw list, but about background draw list as well. And in imgui it's called ImDrawList anyway.

**Comment by thomcc** [comment]
Oh, hm, yeah, that seems reasonable. If you PR that (and the changes needed to fix your issue that you mention) I don't see a reason not to accept them off the top, assuming they fix your issue.

Otherwise, I'm not really around right now, and won't be able to take a look until after the start of the year.

**Comment by nsf** [comment]
Ok, I'll submit a PR sometime later today (in few hours).

**Comment by thomcc** [comment]
Cool, I'll maybe not be able to review until tomorrow, depending. Thanks for digging into this and submitting such a descriptive issue.

**Comment by rmccrystal** [comment]
Having the same issue

**Comment by thomcc** [comment]
Going to try and get a release out this weekend.
