### ISSUE TITLE
UI::is_key_released may be easy to use incorrectly because of u32 key_index

### ISSUE THREAD

**Issue by benmkw** [imgui-rs/imgui-rs#415]
I had the following bug:  `ui.is_key_released(imgui::Key::A as u32)` which should have been `ui.is_key_released(ui.key_index(imgui::Key::A))`.

If a breaking change would be acceptable I would think making `is_key_released` accept a `Key` (or marking it a method on the Key and passing the ui) would be harder to use incorrectly. This also applies to other related methods which take a `key_index`.

**Comment by thomcc** [comment]
That sounds reasonable to me (PR welcome). The next release will be breaking already.
