### ISSUE TITLE
Columns do not work properly

### ISSUE THREAD

**Issue by krallznut** [imgui-rs/imgui-rs#422]
I'm trying to use the columns and I can't find how to end columns mode. Here's my code :

```rust
for i in 0..len {
    let id: ImString = i.to_string().into();
    TreeNode::new(&id).framed(true).build(ui, || {
        ui.columns(2, im_str!("Hello"), false);

        shader_entries_header(ui);

        ui.text("Yolo");
        ui.next_column();
        ui.text("Swag");
        ui.next_column();

        ui.separator();
    });
}
```

Here's what it looks like : 

![image](https://user-images.githubusercontent.com/16839118/104829209-a76c2b00-583f-11eb-8212-6feff8b7da87.png)

In the original `ShowDemoWindow()` C++ code, a table end with `ImGui::Columns(1)`. I can't find the equivalent in `imgui-rs`.

I'm using `imgui-rs 0.6.1`
My operating system is a Linux.

I don't mind contributing to fix the issue myself but I would need some inputs from a contributor.

**Comment by francesco-cattoglio** [comment]
> In the original ShowDemoWindow() C++ code, a table end with ImGui::Columns(1). I can't find the equivalent in imgui-rs.

For imgui-rs, the equivalent is doing exactly the same: just call 
`ui.columns(1, im_str!("Hello"), false);`
when you are done drawing the columns.

**Comment by sanbox-irl** [comment]
@krallznut did the above help out? ImGui has also stabilized the new tables API which will be coming out soon to imgui-rs (you can pull master and use it now if you want)

**Comment by krallznut** [comment]
Yes it works fine thanks for the quick answer! I was also secretly hoping for the new table API so I'm very happy to hear that it's coming soon! I'll sure checkout master. You guys rock!

**Comment by sanbox-irl** [comment]
just to be clear @krallznut we're still working on the rust backing to the tables API, so for now, you'd have to drive it yourself on a fork, but it's on the todo list soon!
