### ISSUE TITLE
Missing binding for CtrlEnterForNewLine for InputType

### ISSUE THREAD

**Issue by bjadamson** [imgui-rs/imgui-rs#423]
Hello, I noticed that a binding for the [CtrlEnterForNewLine ](https://github.com/imgui-rs/imgui-rs/blob/17be09eaef666b83d5bff331e69f716b0b1543ce/imgui/src/legacy.rs#L105) flag isn't exposed. From what I can tell, it should be exposed [here](https://github.com/imgui-rs/imgui-rs/blob/17be09eaef666b83d5bff331e69f716b0b1543ce/imgui/src/input_widget.rs#L90).

I'm wondering if this was intentional or just an oversight?

Thanks (:

**Comment by sanbox-irl** [comment]
You should be able to access this just using the `.flags`  [here](https://github.com/imgui-rs/imgui-rs/blob/17be09eaef666b83d5bff331e69f716b0b1543ce/imgui/src/input_widget.rs#L12) like `.flags(imgui::ImGuiInputTextFlags::CtrlEnterForNewLine)`. Not that this API isn't excellent at the moment, and there will likely be some work done on it soon (https://github.com/imgui-rs/imgui-rs/issues/430).

**Comment by sanbox-irl** [comment]
Going to close. Thank you for submitting an issue!
