### ISSUE TITLE
Update to imgui 1.80

### ISSUE THREAD

**Issue by thomcc** [imgui-rs/imgui-rs#425]
Been extremely sick lately, so I haven't been able to work on this.

That said, https://github.com/ocornut/imgui/releases/tag/v1.80 was just cut so I'm filing this to remind myself.

**Comment by sanbox-irl** [comment]
Should we be trying to also switch over to the string_view branch as well? I know this repo tracks imgui's master, but since that branch essentially exists *for* imgui-rs and other non-C++ projects, it seems like we should start testing it. At least as a branch in this repo

**Comment by thomcc** [comment]
That sounds reasonable to me.
