### ISSUE TITLE
Add `_ext` functions for magic numbers and break old functions (work around lack of default arguments)

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#427]
Hello! Wow I have made three issues right in a row, and sorry for that.

Right now, there are a few magic numbers in ImGui, but probably the two biggest that a newbie will run into are:

1. ui.same_line(0.0);
2. ui.button([0.0, 0.0]);

I believe we should redo each to be like this:

```rust
    /// Call between widgets or groups to layout them horizontally.
    ///
    /// X position is given in window coordinates.
    pub fn same_line(&self) {
        unsafe { sys::igSameLine(0.0, -1.0f32) }
    }

    /// Call between widgets or groups to layout them horizontally.
    ///
    /// X position is given in window coordinates.
    pub fn same_line_ext(&self, pos_x: f32) {
        unsafe { sys::igSameLine(pos_x, -1.0f32) }
    }
```

This would be a breaking change, but is a simple way that we can make imgui less confusing.

The problem is that in ImGui, you don't actually deal with the magic 0.0 because of default arguments -- an imgui C++ dev needs to only issue `ImGui::SameLine()` and move on. Ironically, with our current setup, we require Rust developers (not traditionally lovers of magic numbers!) to be more familiar with ImGui's magic numbers than C++ developers!

Alternatively, we could:
1. Keep the current `same_line` and `button` and others with their current name, and add a new function like `same_line_default_spacing`. This would have a huge advantage of not being a breaking change to users, and more importantly, it might clearly indicate what the magic number is doing. However, this is much more verbose, and it makes imgui-rs look different from ImGui C++ -- which is a problem for users, since C++ code is still by far the biggest source of ImGui examples to look at.
2. We could simply better document those magic numbers with each function. That would save someone from doing the googling I did initially, probably, but I suspect the compiler will not obey our sweet doc comments.

Let me know what ya'll are thinking!

**Comment by dbr** [comment]
+1 to this, would make the library nicer to use

Only suggestion I'd maybe is maybe using a more descriptive extension than `_ext` - e.g `same_line()` and `same_line_pos(50.0)`, `button()` and `button_size([100.0, 20.0])`

**Comment by toyboot4e** [comment]
Another option would be a trait like this:

```rust
pub struct X;

impl X {
    pub fn f(&self, a: f32) -> f32 { a }
}

pub trait XDefaults {
    fn f(&self) -> f32 { 0.0 }
}

impl XDefaults for X {}
```

Adding such a trait is not a breaking change. [Example on Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d84b2fa7ad50cc40c685eb072e0644d4)

**Comment by thomcc** [comment]
I really like this idea. I don't like how verbose we are compared to the C++ API

(I think the trait version wouldn't work, but I think the author figured that out).

**Comment by sanbox-irl** [comment]
Alright ya'll -- I'll PR this in over the weekend.

Right now, the two ones are *probably* `same_line` and `button`, but I'll take a look at others

**Comment by sanbox-irl** [comment]
aaand the PR is done. about a week late; sorry about that. For those to complain about: <https://github.com/imgui-rs/imgui-rs/pull/452>

@dbr your advice was good and I took it! good suggestion

**Comment by dbr** [comment]
This can be closed I think! 🥳
