### ISSUE TITLE
Callback input flags for Text/Floats/etc are more or less useless right now

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#430]
Hi all,

I'm planning on spending some effort rewriting the inputflags system in the next few days. 

On TextInput, we allow users to indicate that they would like a callback with a given flag, but, somewhat hilariously, we have not implemented a way to provide a callback (*wah wah*), so you can be like "i would like a per char callback", but can't actually give it one, and Dear ImGui apparently just ignores your flag then. There are some comments which indicate a boxed trait object approach, but I suspect just a mutable pointer generic over a trait will be sufficient (I do not think imgui needs to hold onto this struct, but it may, so I'll look into it).

If anyone else is working on this/had some PR to merge, lmk so I don't spend the effort unnecessarily!

**Comment by thomcc** [comment]
Good point. Yeah, you shouldn't need box here IIUC.

**Comment by luke-titley** [comment]
Was any progress made with this issue ?

**Comment by sanbox-irl** [comment]
Haven't gotten around to it yet!  There's a question here about how we handle strings that I think this should wait on. @thomcc has been thinking on that, but I'm not sure what his thoughts are yet

**Comment by luke-titley** [comment]
Oh right. What's the issue with strings ? I guess we'd need to pass a boxed FnMut or Fn to the builder and wrap that in a c callback ?

**Comment by AngelOfSol** [comment]
I've started implementing this, but I'm running into API design choices that I'd like feedback on (my comments are in the PR's code changes).

**Comment by thomcc** [comment]
Yeah I see, those are some tricky questions. I can probably get to it later next week sometime. I *think* @sanbox-irl has more experience with this code anyway, although possibly if they're busy I'll get to it before them.

**Comment by sanbox-irl** [comment]
will take a look!
