### ISSUE TITLE
Contributor Docs / Contributor Tags

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#436]
We should probably add some contributor docs in the top level of the crate -- we can probably copy Rust analyzer's structure https://github.com/rust-analyzer/rust-analyzer/tree/master/docs but just do `docs`.

User docs are kind of hard for us to do since imgui's visual, and the C++ demo is sufficient. 

@thomcc what are your thoughts about tagging "beginner friendly" issues too? This repo is both very large, but actually quite easy to contribute to, especially on the actual API. It'd be nice to expand who's contributing beyond those who had to.

We can have this be the end dest for https://github.com/imgui-rs/imgui-rs/issues/435

**Comment by dbr** [comment]
We now have a `docs` folder with development docs, and #664 may move towards a user-facing documentation

I do like the beginner-friendly issue idea - made a [`good-first-issue`](https://github.com/imgui-rs/imgui-rs/labels/good-first-issue) label for this
