### ISSUE TITLE
ListClipperToken survived the token rewrite and should be rewritten to be less OOP

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#438]
Absolutely no idea what's going on with that, no idea what it does. I'm going to leave it for 0.7 and take a look at nabbing it in 0.,8 with a breaking change that makes it less odd.

**Comment by dbr** [comment]
I've added an example in #510 showing what ListClipper does - basically calculates which items are visible in a scroll window, so you can render only those items. I used it recently to create a table which happily displays millions of entries (where just calling `ui.text(...)` for everything and having the viewport clipping handle it would be catastrophically slow)

I'm not too sure if there is a reason why the `clipper.step()` call might be necessary in more complex use cases, or if it's an artifact of imgui's C++ subset, but it seems like the Rust API could be simplified to a iterator:

```
let mut clipper = imgui::ListClipper::new(lots_of_words.len() as i32)
    .items_height(ui.current_font_size())
    .begin(ui);

for row in clipper {
    ...
}
```

**Comment by sanbox-irl** [comment]
Ah thank you! I merged that PR in and feel okay closing this one down
