### ISSUE TITLE
Removing `imgui-gfx-renderer`?

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#444]
Would it make sense to remove the renderer which uses the deprecated `gfx` crate?

> https://github.com/gfx-rs/gfx#the-gfx-crate
>
> This repository was originally home to the [`gfx`](https://crates.io/crates/gfx) crate, which is now deprecated. You can find the latest versions of the code for that crate in the [`pre-ll`](https://github.com/gfx-rs/gfx/tree/pre-ll) branch of this repository.

and the last release of `gfx` (0.18.2) was close to a year ago and is presumably the final release

The reason it might be worth removing is it is maybe (at least it was to me) a little confusing as the `gfx` repo is still active, but it is now being used for the `gfx-hal` package. So I initially assumed the ` imgui-gfx-renderer` was as-valid a thing to use for a new project as `glium`. To add further confusion, the [gllium repo says it is "no longer actively developed by its original author"](https://github.com/glium/glium) (which on first glance reads like the project is dead, but it's actually just maintained by different people - edit: made issue about clarifying this with glium project [here](https://github.com/glium/glium/issues/1912))

I can see the value in having more than one example integration codebase - which is probably where #243 comes in I guess!

**Comment by sanbox-irl** [comment]
i am pretty in favor of this. It's useful to have the rendering backends in *some* form for CI to identify any reversions, but it'd be nicer instead if we could figure out how to check out imgui-wgpu and use that as a test bench too.

**Comment by sanbox-irl** [comment]
@thomcc opinions?

**Comment by thomcc** [comment]
In favor of it, but not really in favor of having `glium` (which is very lightly maintained and not commonly used) be the only example impl here. I think long term we probably want:

- A glow renderer instead of the glium renderer.
- A wgpu renderer instead of the gfx renderer, although for this I suspect the community does a better job than we would (or than I would anyway), so it requires more thought / coordination.

That said, that stuff doesn't need to block removal of the gfx one.

**Comment by sanbox-irl** [comment]
I do not believe there is a currently publicly available glow implementation. My own imgui bindings are using `glow` however, and are closely based on the dear imgui opengl bindings. I doubt the https://github.com/Yatekii/imgui-wgpu-rs would be interested in being consumed by us, but maybe they are? I can reach out

**Comment by dbr** [comment]
@Hperigo has recently started working on https://github.com/Hperigo/imgui-glow-renderer

Played around with it today and seems quite promising (only been going for a few weeks but pretty much worked as expected - missing some obvious things like changing cursors, and things mentioned in the README like custom texture support - but certainly not from being pretty usable)

> In favor of it, but not really in favor of having glium (which is very lightly maintained and not commonly used) be the only example impl here.

> but it'd be nicer instead if we could figure out how to check out imgui-wgpu and use that as a test bench too

I agree this is a good thing to retain. I wonder if it's just a case of the examples having `imgui-whatever-renderer = "1"` as a dependency, along with

```rust
[patch.crates-io]
imgui = { path = "../imgui/" }
```

so the CI builds will pull in the latest published release of the renderer, and build against the to-be-tested imgui-rs

Assuming that actually works, then the imgui-rs repo could still have `imgui-examples`, `imgui-glow-example`, `imgui-wgpu-examples`, but the actual integraiton code could live elsewhere and be separately versioned (which seems like a good thing I think?)

**Comment by sanbox-irl** [comment]
Hello!

I am planning on doing the following now that `imgui-glow-renderer` has been stabilized:

1. remove the gfx_renderer from this repository, place it in a separate repository under this org, and kill it there.
2. glium, despite supposedly not being maintained, is chugging along just fine. I'd be in favor of keeping it around, even though `glow` is my personal preference.
3. finally, add an sdl2 crate to mirror the winit crate.

**Comment by dbr** [comment]
It has been removed (well, it is now [enjoying a quiet retirement here](https://github.com/imgui-rs/imgui-gfx-renderer))
