### ISSUE TITLE
More visiblity on auto-sizing of widgets

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#448]
I only recently realized that you can do, for example,

```rust
if ui.button(im_str!("Run"), [0.0, 0.0]) {
}
```
and imgui will work out a good size for the button, similarly for one axis this works:

```rust
if ui.button(im_str!("Run"), [100.0, 0.0]) {
}
```

I'm used to Qt, so when there was a size, I assumed 0.0 just meant a.. very, very small button..

I can't think of a neat solution to make this obvious in the method signature - e.g requiring `ui.button(im_str!(...)).build()` to allow `ui.button(...).width(100.0).build()` seems clunky and excessive, and making size an `Option<[f32; 2]>` is probably even clunkier

Maybe just mentioning this in some of the more commonly used widget doc-comments would be enough to make this discoverable enough? Additionally using it in some of the examples with comments explaining it might help (e.g `hello_world` probably shouldn't explicitly specify the window height, and explain that using 0.0 works on most widgets) :thinking:

**Comment by sanbox-irl** [comment]
How would you feel if `ui.button` only took one argument, and by default assumed `0.0`, and we also exposed a `ui.button_ext` which took both?

I've mentioned the idea here:

https://github.com/imgui-rs/imgui-rs/issues/427
