### ISSUE TITLE
Why only part of keyboard inputs provided?

### ISSUE THREAD

**Issue by Danielmelody** [imgui-rs/imgui-rs#455]
```rust
#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
pub enum Key {
    Tab = sys::ImGuiKey_Tab,
    LeftArrow = sys::ImGuiKey_LeftArrow,
    RightArrow = sys::ImGuiKey_RightArrow,
    UpArrow = sys::ImGuiKey_UpArrow,
    DownArrow = sys::ImGuiKey_DownArrow,
    PageUp = sys::ImGuiKey_PageUp,
    PageDown = sys::ImGuiKey_PageDown,
    Home = sys::ImGuiKey_Home,
    End = sys::ImGuiKey_End,
    Insert = sys::ImGuiKey_Insert,
    Delete = sys::ImGuiKey_Delete,
    Backspace = sys::ImGuiKey_Backspace,
    Space = sys::ImGuiKey_Space,
    Enter = sys::ImGuiKey_Enter,
    Escape = sys::ImGuiKey_Escape,
    KeyPadEnter = sys::ImGuiKey_KeyPadEnter,
    A = sys::ImGuiKey_A,
    C = sys::ImGuiKey_C,
    V = sys::ImGuiKey_V,
    X = sys::ImGuiKey_X,
    Y = sys::ImGuiKey_Y,
    Z = sys::ImGuiKey_Z,
}
```
where is the key `B`, `D` ... and everything else?

**Comment by sanbox-irl** [comment]
Those are the keyboard inputs which imgui *itself* tracks. You set up your keyboard bindings which allow you to ferry keyboard inputs throughout your application using the keymaps API. Check out the winit platform implementation, and see how it handles keys.

Effectively, those are just the keys which imgui needs to operate (it doesn't actually ever listen to `b`, `d` or anything else!)

**Comment by dbr** [comment]
I ran into the same difficulty today, trying to make a shortcut as obscure as `ctrl+q`

## History

In imgui-rs 0.6 you could do

```rust
if ui.is_key_down(winit::event::VirtualKeyCode::Q as u32) {
    println!("Cool");
}
```
..assuming you were using the `imgui-winit-support` or similar.

In imgui-rs 0.7.0 was a change (#416) which made this harder, as the key functions take `imgui::Key` directly - which I think is a better API, but is currently limited to a very small subset of keys (A/C/V/X/Y/Z etc as mentioned)

## Workaround

I think the workaround for 0.7 is as described in previous comment here and one on #416:

```rust
if ui.io().keys_down[winit::event::VirtualKeyCode::Q as usize] {
```

However I don't think there is a simple equivalent to `is_key_released` etc, as you would have to reimplement the state tracking (same with key-repeat handling)

## Future

There is an upstream PR to add more keys to this map:

https://github.com/ocornut/imgui/pull/2625

Once merged the API for simple case of, say, "I want to check if Q was released" will be good.

For "more obscure" keys, it still seems like it's necessary to be able to pass in a key code.

I wonder if we can add an extra item to the `imgui::Key` enum like

```
enum Key {
    Tab = sys::ImGuiKey_Tab,
    LeftArrow = sys::ImGuiKey_LeftArrow,
    RightArrow = sys::ImGuiKey_RightArrow,
    ...,
    Other(u32),
}
```

Then you can do both `ui.is_key_released(imgui::Key:A)` and  `ui.is_key_released(imgui::Key:Other(9999))`

**Comment by thomcc** [comment]
I think that needs to match the layout of a C enum for FFI. I also don't love it because you could have `Key::Other(sys::ImGuiKey_Tab as _)` and stuff gets weird to handle

I think we should just readd the functionality that was removed in https://github.com/imgui-rs/imgui-rs/pull/416.

**Comment by dbr** [comment]
I think the FFI aspect is fine as the Key is just a fancy integer, but.. a much larger issue is Rust doesn't currently allow this

```rust
enum PrototypeKey{
    A = 1,
    B = 2,
    Other(u32),
}
```
This errors with `error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants` ([tracking issue](https://github.com/rust-lang/rust/issues/60553))

So, yep, reintroducing those key-by-index methods seems like the best solution for now!

**Comment by dbr** [comment]
Made a PR for this, https://github.com/imgui-rs/imgui-rs/pull/463
