### ISSUE TITLE
How to set color of context

### ISSUE THREAD

**Issue by a1ien** [imgui-rs/imgui-rs#460]
I understand that imgui uses the provided context. But how I can set color of this context.
For example gluim. Is that variable for color? https://github.com/imgui-rs/imgui-rs/blob/1c5d8c368cd48945e17a900b290bf8416c46c3d1/imgui-glium-renderer/src/lib.rs#L108
And can I in some way change color from https://github.com/imgui-rs/imgui-rs/blob/master/imgui-examples/examples/support/mod.rs this code?

**Comment by sanbox-irl** [comment]
Tell us more what you mean. That line right there describes the *vertex* of a single quad. So if you're rendering, say, a square and it needs to be tinted a certain color, then each vertex will have that data individually inside it (this makes batching calls much faster then setting that via a uniform or something).

The "context" itself is just a handle on ImGui really -- it doesn't have a "color". You use the context to generate user interfaces which produces vertexes which *may* be colored. You can adjust the style of the basic UI that gets made (which probably will be reflected in the vertex data) using the style editor! try `ui.show_demo` to access the style editor (it's in the menu bar)

**Comment by a1ien** [comment]
I mean context color where imgui window is not present. Current examples use white color. How change this color.

**Comment by sanbox-irl** [comment]
Ohhh do you mean the *clear* color? Like what the background color underneath the windows are?

**Comment by sanbox-irl** [comment]
If so, that'd be set on this line here (not by imgui -- this is a graphics API thing):

https://github.com/imgui-rs/imgui-rs/blob/master/imgui-examples/examples/support/mod.rs#L122

**Comment by a1ien** [comment]
Thanks. Tried to find this line for couple of hours :)
