### ISSUE TITLE
How to use  the closure variant  of  menu_bar API?

### ISSUE THREAD

**Issue by selassje** [imgui-rs/imgui-rs#465]
Instead of remembering to close the tokens, there are APIs like menu() that take closures.  I want to do something like :
````
      ui.main_menu_bar(|| {
                ui.menu(
                    im_str!("File"),
                    true,
                    || {
                   //do stuff
                    },
                );
            })
````
I could not find any examples of the usage.

**Comment by sanbox-irl** [comment]
Good news @selassje -- we agree. in the current master, tokens will close themselves permissively on drop!

What you have there looks fine on sight, though I'm using master where the API has slightly changed.

**Comment by sanbox-irl** [comment]
We've been moving away from the closures because they'll often present borrowing issues, especially as you pass things and structs into the closures.

**Comment by selassje** [comment]
I see, well, the code above gives me indeed borrowing issues on version 0.5.0:

closure requires unique access to `ui` but it is already borrowed
closure construction occurs here

**Comment by sanbox-irl** [comment]
Indeed -- that's why we don't use the closure variations. You probably could fix it in your own code with clever enough work, but simply using the token variants now will solve it. In the next update, you won't need to manually drop the tokens!

**Comment by selassje** [comment]
ok, thanks, I'm using a rather clumsy macro as a workaround, but I will definitely switch to droppable tokens when they are released.

**Comment by sanbox-irl** [comment]
👍
