### ISSUE TITLE
Build method closures returning a user-specified type rather than ()

### ISSUE THREAD

**Issue by AngelOfSol** [imgui-rs/imgui-rs#467]
Often times when I'm using the `.build(ui, || { ... })` APIs, I want to return data to the outside scope.  It's kind of inconvenient as it is right now because I have to create a mutable variable outside the scope.  I'm wondering if we could consider changing the return type of these closures to something more usable to the user.

Here's an example re-definition for the `build` method on PopupModal, to explain what I mean:
Today:
```Rust
pub fn build<F: FnOnce()>(self, ui: &Ui<'_>, f: F) {
    if let Some(_popup) = self.begin_popup(ui) {
        f();
    }
}
```
Suggestion:
```Rust
pub fn build<F: FnOnce() -> T, T>(self, ui: &Ui<'_>, f: F) -> Option<T> {
    self.begin_popup(ui)
        .and_then(|_popup| f())
}
```
Alternative:
```Rust
pub fn build<F: FnOnce() -> T, T>(self, ui: &Ui<'_>, f: F) -> Option<T> {
    if let Some(_popup) = self.begin_popup(ui) {
        Some(f())
    } else {
        None
    }
}
```

**Comment by thomcc** [comment]
This is a good idea.

**Comment by AngelOfSol** [comment]
I dunno if there's any design decisions to be had, but I'd be happy to draw up a PR to do this.

**Comment by AngelOfSol** [comment]
Another benefit I just realized is that it lets `?` propagation actually work properly through these closures. (though some turbofish might be required in some cases).

**Comment by thomcc** [comment]
Go for it. The ones with the

```rust
pub fn build<F: FnOnce() -> T, T>(self, ui: &Ui<'_>, f: F) -> Option<T>
```

signature seems best to me. Feel free to comment if you hit issues or whatever.

**Comment by thomcc** [comment]
Ah, hm, if we expect turbofish it might be better as `fn build<T, F: FnOnce>` to put the thing you're likely to turbofish first. 

That said, you also could do

```rust
...build(ui, || -> Blah { ... })
```

which would avoid turbofish. So I don't have strong opinions.

@sanbox-irl any thoughts?
