### ISSUE TITLE
CollapsingHeader does not have begin/end API

### ISSUE THREAD

**Issue by cosmicchipsocket** [imgui-rs/imgui-rs#481]
While many widgets can be used with the begin/end API (ChildWindow, TabBar/TabItem, TreeNode, etc.), the CollapsingHeader does not. It would be nice to be able to have this so that creating such a header would leave the Ui object free to be borrowed elsewhere.

Could begin/end be added to CollapsingHeader?

**Comment by sanbox-irl** [comment]
I added a `begin` passthrough, but the `begin/end` apis are really for things that require an `end`, and `CollapsingHeader` weirdly just returns a `bool`! I don't know how it works internally -- I've personally not used it, but adding the `begin` didn't seem like a bad call
