### ISSUE TITLE
How can I remove the containing Window?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [imgui-rs/imgui-rs#487]
![image](https://user-images.githubusercontent.com/39968/119280400-d9fdb880-bc63-11eb-90ec-ea0764996dde.png)
I created a demo program. How can I remove the yellow highlighted part (the containing window)? Thanks.

Btw, this is my testing program.
https://github.com/0x7FFFFFFFFFFFFFFF/gui1

**Comment by thomcc** [comment]
Can't repro. If you try in the examples in this repo, are they yellow?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Can't repro. If you try in the examples in this repo, are they yellow?

Oh, you misunderstood. The yellow part was edited manually by me using PhotoShop. What I want is hiding the containing window (the yellow part with the title "main.rs") and only show the dark small window(in the center of the snapshot).

**Comment by thomcc** [comment]
Ah, yeah, that's not what imgui is for. It's mostly for overlay gui in interactive programs like games. It can't manage windows on its own.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Ah, yeah, that's not what imgui is for. It's mostly for overlay gui in interactive programs like games. It can't manage windows on its own.

Thanks for the explanation!

**Comment by JMMlw** [comment]
> Ah, yeah, that's not what imgui is for. It's mostly for overlay gui in interactive programs like games. It can't manage windows on its own.

In cpp and go imgui you have examples on varous forums of projects without main window.

**Comment by dbr** [comment]
True, you can emulate this by making a single imgui window, and setting its size to the full area of the OS window (i.e `ui.io().display_size`)

https://github.com/imgui-rs/imgui-rs/issues/669#issuecomment-1257644053

Also the viewport implementation in #619 will make this easier and more useful
