### ISSUE TITLE
Fedora packaging need license and readme file

### ISSUE THREAD

**Issue by remilauzier** [imgui-rs/imgui-rs#493]
Hi.
Fedora need to have access to the license and the readme file in the crate source. \
A ``include = [ "README.markdown", "LICENSE-APACHE", "LICENSE-MIT"] should be sufficent for fedora.

**Comment by thomcc** [comment]
So, these files are in the repo root, which is outside the directory of each package. I don't believe that `include` works for this.

Do you happen to know if symlinking them to the right place and then including that works when publishing?

**Comment by thomcc** [comment]
Also, can you elaborate why you need the README? The license makes sense, but the readme is surprising.

**Comment by remilauzier** [comment]
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation

Fedora want to package every bits of documentation concerning a package, Even the readme file.

You can look at: ``%license LICENSE-APACHE LICENSE-MIT %doc CHANGELOG.md CONTRIBUTING.md README.md src/doc`` 
https://src.fedoraproject.org/rpms/rust-cargo/blob/rawhide/f/rust-cargo.spec

I am not sure for the symlink. @eclipseo should be able to answer that question.

**Comment by thomcc** [comment]
It seems like maybe the include path is able to go outside of the package, even though this isn't documented.

**Comment by thomcc** [comment]
Yeah, this should work: https://github.com/rust-lang/cargo/blob/cc75485f72a6aaf871d4368b4b8eb01046f3af28/tests/testsuite/package.rs#L1606-L1622

**Comment by remilauzier** [comment]
Thanks for your time. that should ease distro packaging.

**Comment by thomcc** [comment]
Damn, I was mistaken. That test is testing the behavior of `license-file = ...` not `include = [...]` and I can confirm that `include` does not work when done locally. Ugh.
