### ISSUE TITLE
Question about imgui packaging

### ISSUE THREAD

**Issue by remilauzier** [imgui-rs/imgui-rs#497]
Fedora would like to know if it would be possible to unbundle imgui and package it seperatly as an option.
https://bugzilla.redhat.com/show_bug.cgi?id=1968733#c1

**Comment by thomcc** [comment]
Unfortunately, it would be hard to enforce the version matches (possibly not on fedora, but in general), which could lead to undefined behavior.

So I'm not sure.

**Comment by remilauzier** [comment]
Totally understand. It is not an obligation for fedora, so it's ok.
