### ISSUE TITLE
Is it possible to integrate with C++ imgui?

### ISSUE THREAD

**Issue by rmccrystal** [imgui-rs/imgui-rs#498]
I have a program in C++ that already uses imgui and renders using imgui_impl_dx12. Would it be possible to use this crate to interact with my existing imgui rendering code? Perhaps I could replace the crate's bindings with my own bindings?

**Comment by aloucks** [comment]
It should be. The `C` defines and base path for the imgui `C++` code are exported in the build script. They were exported specifically to allow for integrating imgui libraries written in `C/C++`.

https://github.com/imgui-rs/imgui-rs/blob/master/imgui-sys/build.rs#L32

**Comment by dbr** [comment]
The implot-rs project should be a good reference; if I understand correctly it does exactly what you are aiming to do, integrating custom C++ imgui drawing code with imgui-rs

As aloucks mentions, the `build.rs` in imgui-rs sets `DEP_IMGUI_THIRD_PARTY` to the path to cimgui. This is then used in implot to build against the same version:
https://github.com/4bb4/implot-rs/blob/v0.6.0/implot-sys/build.rs#L47-L51

**Comment by dbr** [comment]
Shall close this - feel free to reopen if anything is not clear!
