### ISSUE TITLE
igGetMousePos API not exposed - only igGetMousePosOnOpeningCurrentPopup

### ISSUE THREAD

**Issue by selassje** [imgui-rs/imgui-rs#508]
like in title

**Comment by dbr** [comment]
There is [`ui.io().mouse_pos`](https://docs.rs/imgui/0.7.0/imgui/struct.Ui.html#method.cursor_pos) which exposes the mouse position as a `[f32; 2]` - does that work for what you need?

As far as I can tell, the [`GetMousePos();`](https://github.com/ocornut/imgui/blob/db686ad5222a00bab7caa39f546313522642f57e/imgui.h#L884) method in imgui just returns this value (docs say `shortcut to ImGui::GetIO().MousePos provided by user`) - but I could be mistaken!

**Comment by sanbox-irl** [comment]
Sorry for the very late response, but yup, dbr is right on that! 

Do to some excellent work by a contributor, btw, you can just search for C++ functions in the docs.rs and it will pull up the relevant Rust code as well!
