### ISSUE TITLE
Remove default range from sliders

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#511]
Currently if you do

```rust
let mut number = 0.0;
imgui::Slider::new(im_str!("example")).build(ui, &mut number);
```
..you get a slider which goes from `f64::MIN` to `f64::MAX` which is, probably, almost never useful:
![image](https://user-images.githubusercontent.com/509/129002282-2e6a81c1-0135-4ff6-be39-aaad4de13828.png)
(that's as close as I could get to putting the slider back to it's 0.0 starting point)

This surprised me every time I forget to specify range.. I'd expect f32 or f64 would default to `0..1` range.

It's less clear what to do with the integer types - i8::MIN/i8::MAX etc are probably reasonable defaults. maybe same with i16. However i32 and i64 have same problem as floats and any default would be incredibly arbitrary

In C++ these parameters are not optional (e.g `SliderFloat(const char* label, float* v, float v_min, float v_max, ...)`) which seems like it's probably a good choice

I think this could be done as part of #454 to make this a non-breaking change - e.g `ui.slider(im_str!("..."), &mut number, 0.0, 1.0)` while deprecating `imgui::Slider` - leaves no room for surprises for the default changing

**Comment by sanbox-irl** [comment]
agreed -- this seems reasonable. and also hilarious that this is the default behavior -- i always specify a range since it just makes sense to for a slider

**Comment by sanbox-irl** [comment]
Looking over this, I'm liable to do two things:
1. Change the parameter to take just two parameters: a min and a max -- we're really just passing a tuple around here, and frankly, imgui will not really care if min > max anyway, so using the Range syntax, and yet never running Range as the iterator it is, isn't correct. The Range syntax implies that we're specifying all the values which are valid within the slider, but we're just specifying the maximum bounds of values, so we should just pass those around.
2. Require a range given in the constructor. Only requiring the `ui.slider` method would be sensible, but I think we should just break on this anyway -- most people probably will find it an easy breaking change (also I like the idea of breaking changes right now to improve the codebase).

This will also let us remove the `RangeToInclusive` syntax, which is comedically confusing.

What do you think @dbr ?

**Comment by sanbox-irl** [comment]
so in code,
```rs
    /// Sets the range inclusively, such that both values given
    /// are valid values which the slider can be dragged to.
    ///
    /// ```rust
    /// # use imgui::im_str;
    /// imgui::Slider::new(im_str!("Example"))
    ///     .range(i8::MIN, i8::MAX)
    ///     // Remember to call .build(&ui)
    ///     ;
    /// ```
    /// 
    /// It is safe, though up to C++ Dear ImGui, on how to handle when
    /// `min > max`.
    #[inline]
    pub fn range(mut self, min: T, max: T) -> Self {
        self.min = min;
        self.max = max;
        self
    }
```

and the builder...
```rs
    /// Constructs a new slider builder with the given range.
    #[doc(alias = "SliderScalar", alias = "SliderScalarN")]
    pub fn new(label: &ImStr, min: T, max: T) -> Slider<T> {
```

**Comment by sanbox-irl** [comment]
see pr #514
