### ISSUE TITLE
Tracking Issue for v0.9

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#531]
Hello!

I am titling this `v0.8.1`, but I expect this will actually end up describing `v0.9.0` (we love to make breaking changes around here).

Here are my personal two goals for this release (which should happen *much* faster than `v0.8.0`) and one stretch goal.

1. Documentation. Documentation EVERYWHERE.
Eagle-eyed repo watchers may have notied that `#![deny(missing_docs)]` was added to the repo, commented out. I would like to release the next version of this crate with that lint enabled. Currently, we have an even 300 missing pieces of documentation. That's a lot, and to a degree, we need to solve that by...writing docs. However, on a deeper level, we have kinds of code which is almost purpose built to be annoying to document. Many of our builders attempt to hide bitflags with `bit_flag_name(&mut self, bool)` kinds of methods (for example, `collapsible` on the `WindowBuilder` struct). These create tons of functions and bad namespacing -- instead, I wish we just had a `.flags` method that users provided bitflags to.
Additionally, I'd like to have more examples for the most used widgets. We have a lot of that covered already, but I'll make a list soon of those that are lacking.
This might not be done fully in time for release, but I'd like us to make the effort. However, unless you're **sure** that the code you're going to document won't be edited in this release (if it's on `Ui` for example, it's probably okay), then let's hold off on this till the other points are addressed.
2. Make alternatives to the Builder pattern.
This one is a big complex because we have several approaches we can take. First, the problem itself: builders are annoying to use because the builder struct itself needs to be pulled into scope, and it makes it so that many basic widgets (buttons, `input_text`, etc) are on the `Ui` object, but more interesting widgets (like `Window`) are in some builder that you need to find. Ideally, *everything which Ui can build, Ui should have a method to build it*.
I see us approaching this with a few methods:
    1. `Ui` can create the requisite `Builder` with a method, and we maintain the builder syntax. So to create a window, for example, you could do `ui.begin_window("name", REQUIRED_PARAM).build();`. I think this is a fine idea, and involves probably the least code deletion.
    2. `Ui` uses `with_x` style "overloads" to allow for extra parameters to be passed in. This works, and is quite nice for many, perhaps even the majority, of functions, but really has a tough time for something like `Window`, where there are a LOT of things that can be given to `Window`, and the russian doll of `with_x` gets difficult.
    3. We use a simple `x` and `x_with` pattern, where `x` takes the core required data, and `x_with` passes in an additional paramter of some Struct of Optional data. Carefully use of `Default` and allowing users to `..Default::default()` can make this, possibly, ergonomic. I'd like to take a swing at this in a few weeks. It's worth pointing out that this method is compatible with the second as well (complicated structs get just the `with`, simpler ones get `with_flags`).

3. Okay, big stretch goal: I'd like us to work on our xtask and build system such that we can have features which differentiate the kind of dear imgui we're binding to. The big goal would be, of course, the docking branch (and then people will stop PRing the docking branch at me), and the `string-view` branch. On its face, that's ALREADY a mis-use of cargo features, which should *always* be additive, but I am miscreant who does crimes, so maybe we do it anyway. Otherwise, other ways to handle the docking branch (***without moving the repo entirely to tracking the docking branch -- we are always going to track the mainline dear imgui versions***) would interest me!

If you have any ideas for this release cycle, please list them out! I'd like to figure out a todo list so I can track what we need to get done in a more organized way for this cycle.

**Comment by thomcc** [comment]
`string-view` can be an internal implementation detail, so having both `docking` and `string-view` features enabled can just use `docking`. Ofc, this doesn't *really* work for the `-sys` crate, but that's probably fairly minor, I doubt it has that many direct consumers who would be concerned about feature collisions.

Unfortunately, I think the only way forward for `docking` and `string-view` is to vendor all three (either as submodules or subtrees or something). Note that given the way cargo works, we can't do things like switch branches in the build.rs of the `sys` crate.

**Comment by dbr** [comment]
...released! https://github.com/imgui-rs/imgui-rs/releases/tag/v0.9.0

**Comment by dbr** [comment]
Note the [docs.rs queue](https://docs.rs/releases/queue) seems massively backlogged currently (currently about 4413 builds queued), but seems to slowly be getting through it
