### ISSUE TITLE
ControlFlow::Wait in glow example

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#542]
The (excellent) glow-renderer uses [`Wait`](https://docs.rs/winit/0.25.0/winit/event_loop/enum.ControlFlow.html#variant.Wait), which "suspend the thread until another event arrives"

https://github.com/imgui-rs/imgui-rs/blob/v0.8.0/imgui-glow-renderer/examples/01_basic.rs#L31-L32

On Linux, the examples all work as expected, and run at 60fps as I'd expect

On Windows, it only redraws whenever there is inputs (like moving the mouse) - which sort of makes sense given the description of `Wait`

This seems to be exactly this issue https://github.com/rust-windowing/winit/issues/1619 - but it's not too clear what the outcome of this is

For now I've just changed it to `ControlFlow::Poll` (which I think is default behaviour), but I'm not sure if the examples should be changed to this also, or if it's a bug to be fixed in `winit`, or...?

**Comment by sanbox-irl** [comment]
Let's push the change to `Poll`. The examples should make imgui look good, so even if it's a bit more CPU usage than we'd want, it's still better to run nicely

**Comment by dbr** [comment]
Done in #545. `Poll` is the default behaviour so I've removed the line entirely from most of the examples, but keep reference to it in one of the later ones
