### ISSUE TITLE
Leaky null bytes with InputTextCallback combined with enter_returns_true

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#546]
With current `main` branch as of f00b5707c0e3a4916d15228f2e0b19301424ffc8

```rust
use imgui::*;

mod support;

fn main() {
    let system = support::init(file!());
    let mut buf = String::default();

    system.main_loop(move |_, ui| {
        ui.window("Input text callbacks")
            .size([500.0, 300.0], Condition::FirstUseEver)
            .build(|| {
                struct CB {}

                impl imgui::InputTextCallbackHandler for &mut CB {
                    fn on_history(
                        &mut self,
                        _dir: imgui::HistoryDirection,
                        _data: imgui::TextCallbackData,
                    ) {
                    }
                }

                let mut cb = CB {};
                ui.input_text("Example", &mut buf)
                    .callback(imgui::InputTextCallback::HISTORY, &mut cb)
                    .enter_returns_true(true)
                    .build();
                ui.text(dbg!(&buf));
            });
    });
}
```

Typing `abc` in the input works flawlessly, but if I press backspace twice the buffer is filled with two nulls:

```
[imgui-examples/examples/callback_bug.rs:29] &buf = "a\u{0}\u{0}"
```

Bizarrely only happens with `enter_returns_true` enabled :shrug:

**Comment by sanbox-irl** [comment]
Well, I don't like that.

**Comment by sanbox-irl** [comment]
Frankly this whole abstraction here needs to be cleaned up by me. I kind of hacked it in, as it was better than nothing, but I needs some rigorousness

**Comment by dbr** [comment]
I worked around this with
```rust
self.text = self.text.chars().filter(|x| *x != '\0').collect();
```
and nothing can possibli go wrong

The new callbacks are quite useful btw - I was about to roughly emulate the `on_history` callback before but it was a fragile mess of `set_keyboard_focus_here` calls

**Comment by sanbox-irl** [comment]
Fixed it in the recent commit! Lmk if there's any issues for ya. I added an example for a "test" thing
