### ISSUE TITLE
InputText buffer resizing does not seem to work properly

### ISSUE THREAD

**Issue by birktj** [imgui-rs/imgui-rs#553]
`InputText` does not seem to resize the buffer correctly when multiple characters are added in one frame. In my case I supply an empty String to InputText until `ui.is_item_deactivated_after_edit()` returns true, however this only leads to a single character being added. 

I believe this is caused by never updating the `length` field of the underlying String and thus at most a single character can be added as the length is only updated by one when the `'\0'` char is added in the begining. I think a good solution would be to call `String::from_raw_parts` at the end of `build` to update the length field. Note however that this would probably require searching for the first zero-byte in order to find the length of the string.

**Comment by sanbox-irl** [comment]
Okay, I ended up handling this very similarly to you, but without enough changes to the code that I'll walk through what I did in the PR. Thank you for the issue!
