### ISSUE TITLE
Add full changelogs to releases

### ISSUE THREAD

**Issue by Sejsel** [imgui-rs/imgui-rs#575]
This is more of a discussion topic, really, but it was a pain point for me recently.

The 0.8.0 release had some changes missing from the [Releases changelog](https://github.com/imgui-rs/imgui-rs/releases/tag/v0.8.0), including some breaking changes -- including one that I just spent 3 days debugging (32bit unicode support and the related ABI breakage). I understand the need for brevity, but breaking changes shouldn't be omitted.

It would probably be enough if the release text explicitly mentioned that the `CHANGELOG.markdown` file has extra content. I did look at that file but only skimmed it, so I missed there are extra important details in there. Maybe also mention it separately in the breaking section for people who only skim through the releases changelog to read the breaking changes (not what happened to me, but I can definitely see some users doing that).

**Comment by dbr** [comment]
That's a good point - I do like @sanbox-irl's summary of the release, as the raw changelog is quite dense reading. The notes in Releases do explicitly mention the changelog,

> In addition to all the above, many other smaller, but important, changes were made this cycle. Please see the changelog as always.

..but I agree it should be clearer the full log may contain additional breaking changes ("important" is a bit nebulous in this regard), and, we should make it more convenient to access by linking directly to the CHANGELOG.markdown

We could also include a `## Full changelog` section in the release notes (maybe wrapping the changelog in a collapsible `<details>...</details>` section)

**Comment by thomcc** [comment]
I think we should have the full changelog. If someone is bothering to take a look at the release notes, it's not worth having a secondary page of notes.

This project isn't big enough to warrant that, anyway, especially given that if the notes include "update imgui" there's *already* another page of notes (or two) you might need to read.

> maybe wrapping the changelog in a collapsible <details>...</details> section

I was initially positive on this, but I think we shouldn't hide it, or someone else will miss it.

Also, last I checked, markdown syntax doesn't work inside these, so you might have to manually strip the markdown, possibly replacing with HTML. Wheras just adding `## Full Changelog` and then pasting the contents in sounds like it isn't too much of an ask (and honestly, I think including the full changelog as the release notes is fine — thats largely the reason you keep a release notes file)

**Comment by dbr** [comment]
Yep agreed - `<details>` does appear to do odd things to the markdown, and on further thought there isn't really much benefit to hiding it by default

**Comment by dbr** [comment]
I've retroactively edited this into to the v0.8.0 tag release notes

**Comment by dbr** [comment]
(..and we shall keep this in mind for future releases - having it there for the current release should be as good a reminder as any!)
