### ISSUE TITLE
Remove deprecated im_str

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#576]
As foretold in the 0.8 release notes,

> Currently `im_str!` is deprecated and will be removed in 0.9.0

**Comment by thomcc** [comment]
We've been getting a lot of complaints from people about breaking changes recently, it might be worth keeping it around (along with anything else just deprecated) so that people have more time to migrate.

**Comment by sanbox-irl** [comment]
I'm in favor of removing it still personally. I know we've gotten complaints, but imo, I'm more concerned about the two dropped issues that slipped into release than our breaking changes. Speaking of which, will try to find the time this week to do imgui work -- thanksgiving had me busy the last week with family
