### ISSUE TITLE
Help Wanted: a "bundled" feature for freetype

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#584]
Hello all,

Right now, we get freetype using `pkg` or `vcpkg`. This requires the user to have freetype in osme capacity, but a lot of users won't really care about finding the specifics, and no matter how nice we make the error messages, I suspect many users would like us to handle the install themselves.

SDL2 uses a similar flag here https://github.com/Rust-SDL2/rust-sdl2#bundled-feature.

I'd love for us to have something similar?

**Comment by thomcc** [comment]
Do any of these support this (and are maintained): https://crates.io/search?q=freetype ?

If so, we could conditionally enable `somecrate/bundled` and add an `extern crate somecrate;` to get it all linked in.

It'd be a bit odd for us to own building, compiling, and updating freetype, it's a larger library and doesn't have a trivial build process.

**Comment by dbr** [comment]
It seems like there's only really [`freetype-sys`](https://crates.io/crates/freetype-sys) package maintained by the Piston project - and that doesn't have a `bundled` feature: it just gives instructions on how to install the package for `mingw`, or how to use the precompiled binaries

**Comment by thomcc** [comment]
That sucks. I do think we'd be better off contributing that to them though, rather than owning it ourselves.

**Comment by sanbox-irl** [comment]
Going to go ahead and close this fella -- looks like we'll have to let the universe go its own way
