### ISSUE TITLE
Table API docs missing, Build docs with all-features?

### ISSUE THREAD

**Issue by jestarray** [imgui-rs/imgui-rs#585]
The table api docs is not available on https://docs.rs/imgui/0.8.0/imgui/index.html

**Comment by sanbox-irl** [comment]
ah shit. good find

**Comment by sanbox-irl** [comment]
should have been fixed with https://github.com/imgui-rs/imgui-rs/commit/f04bae561c84cfb9d9921ffc2a2d8b162e10d457

Will have a patch release out in a few hours which will have that commit on it to update docs.rs
