### ISSUE TITLE
Publishing the sdl2-support crate?

### ISSUE THREAD

**Issue by Zeno343** [imgui-rs/imgui-rs#586]
Currently I have to rely on my own fork of an unmaintained sdl2 crate, it would be lovely if I could just grab the crate that's already in the repo from crates.io. Are there any plans to publish the sdl2-support crate?

Edit: I just realized I can add it to my project directly from the git repo. Duh. Still, having a published sdl crate might be a convenience.

**Comment by dbr** [comment]
This will most likely be published to crates.io as part of the next (v0.9) release

In the mean time you can maybe just use it via a git dependency? Something like:

```
imgui-sdl2-renderer = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "92f94510c6092d242c722f697469d098222c42e5" }
```

..although it may require some changes which aren't compatible with the current `imgui 0.8` release

**Comment by Zeno343** [comment]
Yup, per my edit I realized this is a non-issue for me. Glad to know it will be a proper crate in 0.9 though.

**Comment by dbr** [comment]
Excellent :partying_face:

Shall close this as it the sdl2-support crate should be published as matter of course with the next release. @sanbox-irl can reopen if it's useful to have this issue around as a reminder
