### ISSUE TITLE
0.8.1 docs build failing

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#589]
https://docs.rs/crate/imgui/0.8.1/builds/482032

```
[INFO] [stderr] error: Package `imgui v0.8.1 (/opt/rustwide/workdir)` does not have the feature `docking`
```

Took me a while to realize why: 0.8 doesn't have the docking feature (that will be part of 0.9)

**Comment by sanbox-irl** [comment]
Shit! Looks like we're going to 0.8.2

**Comment by sanbox-irl** [comment]
Does anyone know of a way we could have prevented this in CI in the future?

**Comment by dbr** [comment]
0.8.2 fails docs build for different reason :cry:

https://github.com/rust-lang/docs.rs/issues/630

I think I need to update the `exclude = ["third-party/*.json", "third-party/*.lua", "third-party/imgui/*/"]` in `imgui-sys/Cargo.toml` as it's now wrong with the copypaste imgui setup (unrelated to the docs.rs build problem), but also breaking the docs-build by excluding `misc/imgui_freetype.cpp` etc

**Comment by sanbox-irl** [comment]
let me know when we're good to go for gucci 0.8.3?

**Comment by dbr** [comment]
> Does anyone know of a way we could have prevented this in CI in the future?

It wouldn't help with the initial problem (missing `docking` feature), but we should probably have a CI step which uses `cargo package` to test the packaging for crates.io is working (which would catch the missing `misc/imgui_freetype.cpp` problem)

Not sure about the initial problem - [posted here about it](https://users.rust-lang.org/t/ci-for-docs-rs-build/69484)

**Comment by dbr** [comment]
@sanbox-irl Done in PR #595
