### ISSUE TITLE
Glow renderer doesn't work for any OpenGL with minor version = 0

### ISSUE THREAD

**Issue by PieKing1215** [imgui-rs/imgui-rs#598]
**Describe the bug**
When the minor version of opengl is 0, the shaders are incorrectly prefixed with `#version 40` instead of `#version 400`, which causes compilation to fail:
```
0(2) : error C0201: unsupported version 40
0(3) : error C0000: syntax error, unexpected '(', expecting \"::\" at token \"(\"
0(7) : error C7532: global type mat4 requires \"#version 100\" or later
0(8) : error C7532: global type vec2 requires \"#version 100\" or later
0(8) : error C5060: out can't be used with non-varying fragment_uv
0(9) : error C7532: global type vec4 requires \"#version 100\" or later
0(9) : error C5060: out can't be used with non-varying fragment_color
0(14) : error C7532: global type vec3 requires \"#version 100\" or later
0(15) : error C7532: global function ceil requires \"#version 100\" or later
0(17) : error C7532: global function pow requires \"#version 100\" or later
0(19) : error C7532: global function mix requires \"#version 100\" or later
0(25) : error C1503: undefined variable \"uv\"
0(26) : error C1503: undefined variable \"color\"
0(27) : error C7532: global variable gl_Position requires \"#version 100\" or later
0(27) : error C1503: undefined variable \"position\"
```
which causes `AutoRenderer::initialize(gl, &mut imgui).unwrap()` to fail with `Err(Shader(CompileShader(...)))`

**Please describe your environment**
 - imgui-rs and imgui-glow-renderer at 9866a303a2fa18461a9bdb32af73aa716f1d5f81 (latest commit to main at time of writing)
 - Win10, opengl core 4.0

**Other information**
`minor * 10` is clearly the problem here since `0 * 10` is `0` not `00` (same mistake for fragment):
https://github.com/imgui-rs/imgui-rs/blob/9866a303a2fa18461a9bdb32af73aa716f1d5f81/imgui-glow-renderer/src/lib.rs#L934-L944
Upstream they use `major * 100 + minor * 10` which would correctly yield `400`
https://github.com/ocornut/imgui/blob/afffcd5810d030e24056c1a61f27a6eb632f50ed/backends/imgui_impl_opengl3.cpp#L234

**Comment by dbr** [comment]
Fixed by #599 :partying_face:
