### ISSUE TITLE
is there a way to make a custom widget?

### ISSUE THREAD

**Issue by sun-xb** [imgui-rs/imgui-rs#601]

**Comment by dbr** [comment]
Yep - Dear ImGui makes it quite simple to make custom widgets

If you look around the Dear ImGui issue tracker, there is plenty of examples of custom widgets, and most are quite straight forward to translate into imgui-rs syntax

General approach is to use the "ui.invisible_button" to handle clicks/hover-state etc, then you can either combine existing widgets (using `set_cursor_pos` and explicitly sizing widgets), or use the draw list to draw whatever you need

A combination of these two examples should show you most of the relevant API:

- The [custom texture example](https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui-examples/examples/custom_textures.rs#L126-L148) shows how to use the invisible button to do things like respond to mouse-hover
- The [draw list example](https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui-examples/examples/draw_list.rs) shows a tiny bit more of the drawing API
