### ISSUE TITLE
Update to imgui 1.87 (new event based IO)

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#609]
imgui 1.87 was released recently, which contains a large improvement in how IO events are handled (key presses, mouse events, etc)

https://github.com/ocornut/imgui/releases/tag/v1.87

I think given there's a good amount of changes in 0.9, so we should probably start wrapping that up and make a new release whenever time allows, then integrate these changes into the bindings for 0.10

**Comment by cosmicchipsocket** [comment]
I recently hit this bug which is present in the version of imgui currently used by this crate. https://github.com/ocornut/imgui/issues/4640

So bumping the imgui version in general would be appreciated.

**Comment by bmeneg** [comment]
Any update? 1.88 was released already with several bug fixes of 1.87 I/O queue changes.

**Comment by dbr** [comment]
I've not made any progress on this yet. I would like to wrap up the imgui-rs 0.9 release before updating to the new upstream library (the 0.9 release has quite a few breaking changes, but they are almost entirely simple "search+replace to fix" changes - so I think it's better to have the IO queue changes in a separate release as this, in theory, may require some more significant user-facing changes)

There's not much left I'm aware of (tidying up the collapsing header #604, suppressing a build warning from upstream #558, and maybe removing the remains of `im_str!` #576) - once done this is my next priority

**Comment by dbr** [comment]
(I think these changes should also solve #492 and #558 )
