### ISSUE TITLE
Weird InputText bug

### ISSUE THREAD

**Issue by Skovv** [imgui-rs/imgui-rs#612]
Hi there, i have some weird problem(i guess i'm doing something wrong :D). Check code:
`class UiWindow_ProjectSettings : public UiWindow {
public:
    std::string Name, Author;
    char* name;
    char* author;

    void Create() {
        Name = ProjectName;// i gad some crashes and same problems thats why this was
        Author = ProjectAuthor;
        name = (char*)Name.c_str();
        author = (char*)Author.c_str();
    }
    void Update() {
        if (isOpen) {// = true
            ImGui::Begin("Project Settings", &isOpen, ImGuiWindowFlags_HorizontalScrollbar);

            ImGui::InputText("name", name, 50);
            if (ProjectName.length() > 0) ProjectName = name;

           // ImGui::SetNextItemWidth(500);
            ImGui::InputText("author", author, 20);
            if (ProjectAuthor.length() > 0) ProjectAuthor = author;

            ImGui::End();
        }
    }
};
auto win = new UiWindow_ProjectSettings;
win->Create();

... loop:
win->Update();
`

I was checking this and even i have 10 InputTexts and max length of them is <= 20 then there is no problem. If i set 50 then the result is: [https://ibb.co/0MYw1NV](url)
when i am writing in first TextInput after 29chars it's starting to writing in both of them.. Before i had like it's just crash the app when i had 1 TextInput. What am I doing wrong?

**Comment by Skovv** [comment]
![aaa](https://user-images.githubusercontent.com/1405919/154793222-1f2c20a0-f37b-4405-9823-cdfdf5b2fd26.png)

**Comment by thomcc** [comment]
I think your issue should be filed here: https://github.com/ocornut/imgui

This repository is just for the Rust bindings to the Dear Imgui library, which you don't seem to be using.

**Comment by thomcc** [comment]
I'm going to close this issue. Please feel free to reopen if I've misunderstood.
