### ISSUE TITLE
Let SdlPlatform::handle_event return true if an event is handled

### ISSUE THREAD

**Issue by Gosuo** [imgui-rs/imgui-rs#613]
**Is your feature request related to a problem? Please describe.**
While integrating imgui-rs into an existing SDL2 program I need to check if imgui handled an event and then block it from getting sent to the main program.

**Describe the solution you'd like**
Ideally the method [`imgui-sdl2-support::SdlPlatform::handle_event`](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-sdl2-support/src/lib.rs#L170-L211) could return a boolean value if the event was handled or not.

**Describe alternatives you've considered**
Currently, I match the event after sending it to `handle_event` and check if it is one of the handled events. This works fine, but I don't see a reason why this couldn't be integrated into the library method directly. The [C++ ImGui_SDL2](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_sdl.cpp#L244-L302) implementation does this already.

**Additional context**
If there are no objections to this I'm happy to create a pull request myself.

**Comment by sanbox-irl** [comment]
How does the PR look @Gosuo ? I've been working on the repo tonight, so easy to make

**Comment by Gosuo** [comment]
@sanbox-irl Ah perfect, that is exactly what I had in mind. Looks good to me 👍🏼
