### ISSUE TITLE
imgui-winit-support dependency problems

### ISSUE THREAD

**Issue by slackers123** [imgui-rs/imgui-rs#620]
I am building an application that uses imgui and winit so I used the imgui-winit-support crate, but the compiler keeps throwing this error:
```
platform.attach_window(imgui.io_mut(), surface.window(), HiDpiMode::Rounded);
                                       ^^^^^^^^^^^^^^^^ expected struct `winit::window::Window`, found a different struct `winit::window::Window`
```
So I checked the dependencies and everything is up to date:
```
[dependencies]
winit = "0.26.1"
imgui-winit-support = "0.8.2"
imgui = "0.8.2"
```
So I checked the Cargo.lock file and there are two different versions of winit: 
```
[[package]]
name = "winit"
version = "0.25.0"
....

[[package]]
name = "winit"
version = "0.26.1"
```
I don't know what this is caused by or how to fix it so any help is greatly appreciated.

**Comment by dbr** [comment]
Imgui 0.8 uses winit 0.25 by default, thus the two versions being resolved.
Winit 0.26 is available by using features=["winit-26"] (on phone so can't
check, but you might also have to disable default features)

The next release in current 'main' branch will use 0.26 by default

**Comment by slackers123** [comment]
using 
```
imgui-winit-support = {version = "0.8.2", features = ["winit-26"]}
```
works 
thank you
