### ISSUE TITLE
Pass `all-features = true` in the docs.rs metadata

### ISSUE THREAD

**Issue by Jasper-Bekkers** [imgui-rs/imgui-rs#632]
That way it'll show docs for all the features (such as tables-api)

**Comment by dbr** [comment]
I could be mistaken, but I think this is already done - it's just pending a 0.8.3 release (#629), because enabling the freetype feature broke the docs.rs build for 0.8.2

**Comment by dbr** [comment]
Shall close this as it should be solved by #631
