### ISSUE TITLE
Question: Get value from ImVector

### ISSUE THREAD

**Issue by Siliwolf** [imgui-rs/imgui-rs#640]
I am trying to create a custom backend for Raylib with this, and I'm having some issues with ImVector. I am basing my implementation off of a C++ version of this, and it pulled a value from and ImVector, and I can't figure out how to do the same. Here are some pictures:

### **My Code**
![image](https://user-images.githubusercontent.com/76073900/166104210-8c77c545-6119-44ab-b595-02e4018896df.png)
![image](https://user-images.githubusercontent.com/76073900/166104217-07d44bdc-0ac2-4789-8cb7-4dc31c7532cf.png)

### **C++ Code**
![image](https://user-images.githubusercontent.com/76073900/166104222-0167b927-6725-4139-88ac-bd2e8d2c3174.png)
![image](https://user-images.githubusercontent.com/76073900/166104227-05638fa7-c832-4c0d-8366-8d1b9b707022.png)

#### Thanks!

**Comment by dbr** [comment]
I have a suspicion it's not necessary to directly use the `ImVector` (mainly as it's not used for the imgui-glow-renderer or imgui-glium-renderer - they use the `imgui::DrawIdx` instead), but I'm not too sure. Regardless, I think you can use the `as_slice` method to get a `&[ImDrawIdx]` (which you can index into), so something like

    index_buffer.as_slice()[1]

Or possibly tweak your function to `fn rl_imgui_render_triangles(..., index_buffer: &[ImDrawIdx], ...)` and call `as_slice()` earlier
