### ISSUE TITLE
Working SDL2 Example Cargo.toml

### ISSUE THREAD

**Issue by rtpg** [imgui-rs/imgui-rs#641]
The example in `imgui_sdl2_support` works with the following set of dependencies. I'm putting thise here just as a reference, but it would definitely be worth having some details like this in the repo docs themselves.

```
[dependencies]
glow = "0.10.0"
imgui  = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "92f94510c6092d242c722f697469d098222c42e5" }
imgui_sdl2_support = { git = "https://github.com/imgui-rs/imgui-rs.git", package="imgui-sdl2-support", rev = "92f94510c6092d242c722f697469d098222c42e5" }
imgui-glow-renderer = { git = "https://github.com/imgui-rs/imgui-rs.git", package="imgui-glow-renderer", rev = "92f94510c6092d242c722f697469d098222c42e5" }
[dependencies.sdl2]
version = "0.34.5"
default-features = false
features = ["image"]
```

**Comment by tech0tron** [comment]
this is the most unserious set of rust bindings ever concieved

meme library

**Comment by dbr** [comment]
Thanks!

Now 0.9 is released this should now be simpler, roughtly as per
https://github.com/imgui-rs/imgui-rs/blob/v0.9.0/imgui-sdl2-support/Cargo.toml

```
[dependencies]
imgui = { version = "0.9.0" }
sdl2 = "0.34.5"
glow = "0.10.0"
imgui-glow-renderer = { version = "0.9.0" }
sdl2 = { version = "0.34.5", features = ["bundled", "static-link"] }
```
i.e just removing the "path = " section and combining `dev-dependencies` into the main section. You may also need to change the features of `sdl2` depending on your usecase, as you did

Shall close this - hopefully #664 will help simplify this in future by providing easy to copy-paste examples
