### ISSUE TITLE
Run bindgen from imgui-sys/build.rs

### ISSUE THREAD

**Issue by michael-swan** [imgui-rs/imgui-rs#653]
I've made bindings before that constructed the bindings inside of build.rs where bindgen was a build dependency. Why is that not done in imgui-sys?

**Comment by thomcc** [comment]
It has a bunch of downsides. It doesn't work well on Windows, it slows build times down substantially (bindgen is a heavy dependency), can result in surprising breakage, etc. If you are familiar with C, and platform specifics (I am familiar with both), and have a reasonably well-behaved C library (CImgui is well behaved) there's not that much benefit.

It does support some additional use cases, and is absolutely recommendable if you aren't familiar with C and platform-specific details or have a library which is not well behaved, but that isn't the case here.

Anyway, did you have a concrete use case that would be enabled by build-time bindgen? I'm not sure we want to support it, but we'll hear you out.

**Comment by michael-swan** [comment]
Poor Windows support is the only point made that seems legitimate. Open source everything seldom works well on Windows, if you're supporting that you should do all the gymnastics necessary to make Windows happy. Even if it takes 15 seconds to build that would be unnoticeable in any build of ordinary size since builds aren't single-threaded anymore, so that isn't particularly salient. The benefits of having your build system keep C deps in sync with their corresponding Rust bindings is something you know, so I won't go over them. Again, poor Windows support is a valid reason so you're right, you should do things this way because supporting Windows can be a nightmare.
