### ISSUE TITLE
Custom Titlebar

### ISSUE THREAD

**Issue by AZProductions** [imgui-rs/imgui-rs#656]
Is there a safe way to hide the os native titlebar, and replace it with custom imgui components?

**Comment by dbr** [comment]
This is usually referred to as "window decoration", and would be up to whatever library you are using to actually create the window

E.g if you are using winit, then the [`Window::sec_decorations`](https://docs.rs/winit/0.27.1/winit/window/struct.Window.html#method.set_decorations) should hide the OS titlebar etc
