### ISSUE TITLE
Incorrect doc on `push_item_width`

### ISSUE THREAD

**Issue by linw789** [imgui-rs/imgui-rs#661]
`push_item_with` (and related functions) comes with the comment:

```rust
    /// Returns an `ItemWidthStackToken` that may be popped by calling `.pop()`
```

but `ItemWidthStackToken` doesn't seem to have a `pop` function. Instead, it seems that `Drop` should be used. Is the correct usage to create a scope and call `push_item_with` inside it?

**Comment by dbr** [comment]
Yep well spotted, we should fix up these docs. I think this was just missed in the large #440 PR where we moved to using drop for these tokens

> Is the correct usage to create a scope and call push_item_with inside it?

Yep exactly - you can also manually call `.end()` on the token if it's more convinient (which works like the old `.pop()` method)

**Comment by linw789** [comment]
Curious why it's renamed to `end`. Isn't the original name `pop` more appropriate?

**Comment by dbr** [comment]
Thanks for the PR!

It was changed to `.end` as the macro code for the tokens is shared across all similar tokens, including those used for things like `ui.window(...)` (where `.end()` makes more sense)

We could have maybe had separate macros for both an "end token" and "pop token" (or had both methods), but there's not a huge amount of benefit I think (both names are kind of interchangable, and the preferred way is just to use the drop impl)
