### ISSUE TITLE
Decide on and document dev/release process

### ISSUE THREAD

**Issue by dbr** [imgui-rs/imgui-rs#665]
As per #663

We currently don't have a documented approach to how we perform releases, and doing things like backporting changes to old releases

Key points would be:

1. Stable default branch
2. Develop branch with latest unreleased changes
3. Release branches
4. Checks needed before making release
5. Steps to actual publish imgui-rs (e.g release imgui-sys, then imgui; when to bump version numbers, etc)

**Comment by dbr** [comment]
Thanks, that sounds good to me!

I'll make a PR shortly with a document writing that down. If everyone is happy with that doc then we can move on to making a 0.9 release and onwards :partying_face:

**Comment by dbr** [comment]
PR with propsed doc at #672

**Comment by parasyte** [comment]
FWIW, the process described in the document in the new PR is a good development strategy that I have used on several complex projects. Things do get a bit ugly when the stable branches go on for some time as `main` diverges more and more. It makes "just cherry-pick" infeasible after a while. It's great when that's all it takes, though!

**Comment by MarijnS95** [comment]
@parasyte Indeed, I've been running into a similar scenario with a low-level bindings crate where we're cutting down heavily on quick/successive breaking releases. As a consequence I have to pick about 98% of the changes - which are non-breaking fixes or additions only - to stable branches, to the point where I'm considering to target/merge every PR to the stable branch instead, and manually rebase the three-or-so remaining breaking-change commits (via `main`) on top of the stable branch every once in a while.

Alas, it depends on the project and how many breaking changes versus additive development and bugfixes it sees.

**Comment by airways** [comment]
For what it's worth, I like it, big improvement over the current situation!
