### ISSUE TITLE
docking feature not available from crates.io?

### ISSUE THREAD

**Issue by polymonster** [imgui-rs/imgui-rs#671]
Hello,

I am using docking in my graphics engine [hotline](https://github.com/polymonster/hotline).

I have been following the progress for a little while but have never been able to use the `docking` via crates.io. I have included a local copy of `imgui-sys` inside my repo which I can use docking support with, but I now intend to publish to crates.io and when trying to `cargo package` I just get an error saying that docking is not a feature.

```
error: failed to select a version for `imgui-sys`.
    ... required by package `hotline v0.1.0 (C:\Users\alex_\dev\hotline)`
versions that meet the requirements `^0.8.1-alpha.0` are: 0.8.2, 0.8.1

the package `hotline` depends on `imgui-sys`, with features: `docking` but `imgui-sys` does not have these features.
```

This is the same as if I try to add the crate from crates.io and not use my local copy. There are a fair few issues and PR's regarding docking which I have tried to follow all seemingly merged and pointing toward the fact that docking should be supported? I am just struggling to work out how to use the feature. The `0.8.1-alpha.0` includes docking but `0.8.2` doesn't? and the former is not available on crates?

I have a fully featured and working docking / viewport renderer with a Direct3D12 / Win32 backend via windows-rs if you are interested? I would be happy to contribute if this as a rendering backend... I intend to add metal and vulkan backends to hotline as well which would eventually add cross-platform support in the future through the hotline API.

You can check the project [here](https://github.com/polymonster/hotline) and I wrote an article about integrating imgui-sys on my [blog](https://www.polymonster.co.uk/blog/imgui-backend).

Thanks in advance.

**Comment by dbr** [comment]
Sorry for the confusion! The docking support will be released as part of v0.9

The version in latest-revision's Cargo.toml is indeed confusing - but just read `0.8.1-alpha.0` is `0.9.0-dev` or something like that and hopefully makes sense

This is being discussed at #663 - but basically the solution is just "release 0.9" and "do releases more frequently :sweat_smile:

**Comment by polymonster** [comment]
Ahh! thanks for clearing this up. I'll keep an eye out on the milestone now. Cheers ✌🏻

**Comment by dbr** [comment]
0.9 now released!
