### ISSUE TITLE
Cant compile example

### ISSUE THREAD

**Issue by wojtess** [imgui-rs/imgui-rs#674]
System: Ubuntu 22.04.1 LTS
Rust version: 1.64.0

When i execute `cargo test` in `imgui-examples` directory i have error:
```error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcniCWyB/symbols.o" "/home/wojtess/Documents/rust/imgui-rs/target/debug/examples/long_table-72168e59f046abe3.108hhnjlu1ou8azt.rcgu.o" [a lot of paths writed like prev one] "-Wl,-Bdynamic" "-lxcb" "-lxcb-render" "-lxcb-shape" "-lxcb-xfixes" "-lfreetype" "-lfontconfig" "-lfreetype" "-lexpat" "-lm" "-lfreetype" "-ldl" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/wojtess/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/wojtess/Documents/rust/imgui-rs/target/debug/examples/long_table-72168e59f046abe3" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lxcb-shape: No such file or directory
          /usr/bin/ld: cannot find -lxcb-xfixes: No such file or directory
          collect2: error: ld returned 1 exit status```

**Comment by ExtremelyRyan** [comment]
Sounds like you are one directory too deep, make sure you are in the root directory like the README states:

![image](https://user-images.githubusercontent.com/29506997/194628122-a9c7f1b3-4ef5-44ae-bbd8-e638e8862d3a.png)

**Comment by dbr** [comment]
I think you need to install a few libraries required for interacting with X,

`apt install libxcb-shape0-dev libxcb-xfixes0-dev`
..same as what we do for the CI builds here:
https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/.github/workflows/ci.yml#L109

**Comment by wojtess** [comment]
I installed programs that dbr suggested, and changed directory.
 Still have error, but this time diffrent:
 ````  = note: /usr/bin/ld: /home/wojtess/Documents/rust/imgui-rs/target/debug/deps/libsdl2_sys-3b9df72e57393344.rlib(SDL_waylandvideo.c.o): in function `Wayland_VideoInit':
          SDL_waylandvideo.c:(.text.Wayland_VideoInit+0x58): undefined reference to `wl_proxy_marshal_flags'
          /usr/bin/ld: /home/wojtess/Documents/rust/imgui-rs/target/debug/deps/libsdl2_sys-3b9df72e57393344.rlib(SDL_waylandvideo.c.o): in function `display_handle_global':
          SDL_waylandvideo.c:(.text.display_handle_global+0x197): undefined reference to `wl_proxy_marshal_flags'
          /usr/bin/ld: SDL_waylandvideo.c:(.text.display_handle_global+0x216): undefined reference to `wl_proxy_marshal_flags'
          /usr/bin/ld: SDL_waylandvideo.c:(.text.display_handle_global+0x297): undefined reference to `wl_proxy_marshal_flags'
          /usr/bin/ld: SDL_waylandvideo.c:(.text.display_handle_global+0x2d4): undefined reference to `wl_proxy_marshal_flags'
          /usr/bin/ld: /home/wojtess/Documents/rust/imgui-rs/target/debug/deps/libsdl2_sys-3b9df72e57393344.rlib(SDL_waylandvideo.c.o):SDL_waylandvideo.c:(.text.display_handle_global+0x344): more undefined references to `wl_proxy_marshal_flags' follow
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `imgui-sdl2-support` due to previous error````

**Comment by dbr** [comment]
Sorry for the very slow reply!

Did you get this working, or did you give up? :grimacing: 

The above errors are from the sdl integration (`imgui-sdl2-support`), and are just another missing package (possibly something like `libwayland-client0`)

However if you aren't planning to use the SDL support (and use opengl or another backend), you could probably just skip the `cargo test` at the top-level and run the examples as `cargo run --eample hello_world` etc
