### ISSUE TITLE
release imgui-winit-support for winit 0.27

### ISSUE THREAD

**Issue by m4b** [imgui-rs/imgui-rs#677]
Could we get a release of imgui-winit-support for winit 0.27? Other crates like imgui-wgpu-rs need to bump there wgpu version, but this also requires a winit bump to 0.27.

**Comment by m4b** [comment]
it would be nice to get a release... or is this project in danger of being abandoned?

**Comment by dbr** [comment]
Sorry for the delay - not abandonded, we have just all been coincidentally busy the last few months!

imgui-winit-support v0.9 is now released which has winit 0.27 support
