### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by rod6214** [imgui-rs/imgui-rs#678]
I'm trying to figure out how to fix this issue, but yes this could be an issue, for example Visual Studio 2019 is a program that has its own thread and and its cpu consumption at relax state is approximately between 4%-5%.  I suspect there are a lot of code executing in the main thread.

**Comment by rod6214** [comment]
I'm trying to figure out how to fix this issue, but yes this could be an issue, for example Visual Studio 2019 is a program that has its own thread and and its cpu consumption at relax state is approximately between 4%-5%.  I suspect there are a lot of code executing in the main thread.

**Comment by dbr** [comment]
Note: Shortened title, was originally a quote from https://github.com/imgui-rs/imgui-rs/issues/241#issuecomment-513946359
> This is perfectly normal. Immediate mode GUIs construct the entire GUI on every frame, and you're running the example in debug mode. On my system I get ~10-12 % CPU usage in debug mode and <5 % CPU usage in release mode.

**Comment by dbr** [comment]
Not too sure what your question is here - but if you are interested in reducing the CPU usage of an imgui-rs application:

1. As mentioned in your quote, it's to be expected that Dear ImGui uses "some amount" of CPU to redraw every frame.
2. The biggest reduction is to redraw less - e.g see the [comment here about using `ControlFlow::Poll`](https://github.com/imgui-rs/imgui-rs/blob/8329cd7d1774ea23c2255dc4d8a60cbc522c3727/imgui-glow-renderer/examples/glow_04_custom_textures.rs#L39-L42) to only redraw on window events (e.g when user moves cursor). This of course means it's tricky to do things like a blinking cursor or an animated progress bar - but for certain UI's it works well and should reduce idle CPU to about the minimum possible
3. Next step would be to optimise your application code - using a combination of a regular CPU profiler and a memory allocation profiler (e.g [bytehound](https://github.com/koute/bytehound)) should releval places where you can optimse stuff. Avoiding unnecessary memory allocations per-frame is usually the main optimization
4. If you do need to redraw every frame, there is likely room to optimize the Rust bindings, particularly in the renderer. I have no idea how much room for CPU reduction there is here, probably not a huge amount, but the current examples don't put a huge focus on performance (as much as being comprehensible/tweakable example code)
5. Lastly, there may be some room in Dear ImGui itself for optimizations (both in terms of micro-optimizations and bigger features like https://github.com/ocornut/imgui/pull/2749 mentioned in the quoted issue)
