### ISSUE TITLE
Is there a way to separate the id and label for input widgets?

### ISSUE THREAD

**Issue by juliusl** [imgui-rs/imgui-rs#679]
Today as far as I can tell, labels for input widgets must be unique. I'm able to handle that issue today by adding an id to the label, but I've received feedback about what the numbers mean.  

It would be great if there was a solution similar to `Imgui::TreeNode::new(..).label(..)`. However, I'm not sure if this is possible or if there is another solution I can use to scope input widgets.

**Comment by dbr** [comment]
This can be handled the same was as the upstream C++ API, either by:

1. Use `##` symbol to specify the label and ID separately, e.g `ui.button("Click here##button1"); ui.button("Click here##button2")` would give a two buttons with same visible label, but different ID's. Convinient for cases where you have a few staticly defined widgets
2. Using the `push_id_*` methods - [example here](https://github.com/imgui-rs/imgui-rs/blob/8329cd7d1774ea23c2255dc4d8a60cbc522c3727/imgui-examples/examples/id_wrangling.rs#L36) - this is a lot neater if you are dynamically creating the widgets in a loop or similar

The FAQ on the main imgui repo explains this better:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

**Comment by juliusl** [comment]
@dbr thanks a bunch! This is exactly what I was looking for!
