### ISSUE TITLE
How to use imgui-rs with glfw or winit?

### ISSUE THREAD

**Issue by apoorv569** [imgui-rs/imgui-rs#690]
I am fairly new to rust and but I have used `imgui` with `C++`. I don't understand how to use this library with `glfw` or `winit` for windowing stuff. I was not able to find a up to date example, all examples either are not minimal or too old like 4-5 years old.

I do have a minimal example using `imgui-glfw-rs` but that uses an old version of `imgui`. Here is the example.
in `Cargo.toml`
```toml
[dependencies]
imgui-glfw-rs = "0.4.1"
```

and here is `src` file.
```rust
use imgui_glfw_rs::{glfw, imgui, ImguiGLFW};

fn main() {
    let mut glfw_init = glfw::init(glfw::FAIL_ON_ERRORS).unwrap();
    glfw_init.window_hint(glfw::WindowHint::ContextVersion(3, 3));

    let (mut window, events) = glfw_init
        .create_window(
            1024,
            768,
            "imgui-glfw-rs example",
            glfw::WindowMode::Windowed,
        )
        .expect("Failed to create window");

    glfw::Context::make_current(&mut window);
    window.set_all_polling(true);

    gl::load_with(|symbol| window.get_proc_address(symbol) as *const _);
    unsafe {
        gl::Enable(gl::BLEND);
        gl::BlendFunc(gl::SRC_ALPHA, gl::ONE_MINUS_SRC_ALPHA);
        gl::Enable(gl::DEPTH_TEST);
        gl::DepthFunc(gl::LESS);
        gl::ClearColor(0.1, 0.1, 0.1, 1.0);
    }

    let mut im_ctx = imgui::Context::create();

    let mut imgui_glfw = ImguiGLFW::new(&mut im_ctx, &mut window);

    while !window.should_close() {
        unsafe {
            gl::Clear(gl::COLOR_BUFFER_BIT | gl::DEPTH_BUFFER_BIT);
        }

        let ui = imgui_glfw.frame(&mut window, &mut im_ctx);

        ui.show_demo_window(&mut true);

        imgui_glfw.draw(ui, &mut window);

        glfw::Context::swap_buffers(&mut window);

        glfw_init.poll_events();
        for (_, event) in glfw::flush_messages(&events) {
            imgui_glfw.handle_event(&mut im_ctx, &event);
        }
    }
}
```

and I want to use the new version which has the docking feature.

Is there a minimal example of using `imgui` and either `glfw` or `winit` (I am fine with any), without using other stuff.

**Comment by dbr** [comment]
The glow-renderer examples contain about the most minimal example of using winit I'm aware of:
https://github.com/imgui-rs/imgui-rs/blob/v0.9.0/imgui-glow-renderer/examples/glow_01_basic.rs
This should work both with and without the docking feature enabled

The only part I'm not quite clear on is "[..] winit (I am fine with any), without using other stuff" - just using winit alone would mean you can't display anything.

I think some confusion might come from `imgui-glfw-rs` providing both a "platform backend" and "renderer" (in imgui-rs terminology). Generally these two things are organized as two separate crates, one providing the window/event handling (e.g `imgui-winit-support`), and another providing the rendering (e.g `imgui-glow-renderer`). `imgui-glfw-rs` combines these two into one crate, which is perfectly fine (and quite a good idea when the two are very tightly linked), just different

Let me know if that answers your question!

**Comment by apoorv569** [comment]
> The glow-renderer examples contain about the most minimal example of using winit I'm aware of: https://github.com/imgui-rs/imgui-rs/blob/v0.9.0/imgui-glow-renderer/examples/glow_01_basic.rs This should work both with and without the docking feature enabled
> 
> The only part I'm not quite clear on is "[..] winit (I am fine with any), without using other stuff" - just using winit alone would mean you can't display anything.
> 
> I think some confusion might come from `imgui-glfw-rs` providing both a "platform backend" and "renderer" (in imgui-rs terminology). Generally these two things are organized as two separate crates, one providing the window/event handling (e.g `imgui-winit-support`), and another providing the rendering (e.g `imgui-glow-renderer`). `imgui-glfw-rs` combines these two into one crate, which is perfectly fine (and quite a good idea when the two are very tightly linked), just different
> 
> Let me know if that answers your question!

By "without using other stuff" I meant `imgui-glfw-rs` and other crates, I want to use the official and latest versions. 

When I was using `C++` I used `glfw` for windowing and events and `glew` for `gl` stuff. In the link you shared, I see `glow` and `glutin`, if I understand correctly `glow` is like `glew` but what is `glutin`?

Also there is no official `glfw` support?

**Comment by apoorv569** [comment]
> > The glow-renderer examples contain about the most minimal example of using winit I'm aware of: https://github.com/imgui-rs/imgui-rs/blob/v0.9.0/imgui-glow-renderer/examples/glow_01_basic.rs This should work both with and without the docking feature enabled
> > The only part I'm not quite clear on is "[..] winit (I am fine with any), without using other stuff" - just using winit alone would mean you can't display anything.
> > I think some confusion might come from `imgui-glfw-rs` providing both a "platform backend" and "renderer" (in imgui-rs terminology). Generally these two things are organized as two separate crates, one providing the window/event handling (e.g `imgui-winit-support`), and another providing the rendering (e.g `imgui-glow-renderer`). `imgui-glfw-rs` combines these two into one crate, which is perfectly fine (and quite a good idea when the two are very tightly linked), just different
> > Let me know if that answers your question!
> 
> By "without using other stuff" I meant `imgui-glfw-rs` and other crates, I want to use the official and latest versions.
> 
> When I was using `C++` I used `glfw` for windowing and events and `glew` for `gl` stuff. In the link you shared, I see `glow` and `glutin`, if I understand correctly `glow` is like `glew` but what is `glutin`?
> 
> Also is there no official `glfw` support?

BTW that example is not compiling, I copied the `Cargo.toml` and changes the version of `imgui` and `imgui-winit-support` to use just the version number and removed the `path`,

```toml

and I get these errors,
```sh
error[E0433]: failed to resolve: use of undeclared crate or module `glutin`
 --> src/main.rs:7:5
  |
7 | use glutin::{event_loop::EventLoop, WindowedContext};
  |     ^^^^^^ use of undeclared crate or module `glutin`

error[E0432]: unresolved import `glutin`
 --> src/main.rs:7:5
  |
7 | use glutin::{event_loop::EventLoop, WindowedContext};
  |     ^^^^^^ use of undeclared crate or module `glutin`

error[E0432]: unresolved import `imgui_winit_support`
 --> src/main.rs:8:5
  |
8 | use imgui_winit_support::WinitPlatform;
  |     ^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `imgui_winit_support`

error[E0433]: failed to resolve: use of undeclared crate or module `glutin`
  --> src/main.rs:12:31
   |
12 | type Window = WindowedContext<glutin::PossiblyCurrent>;
   |                               ^^^^^^ use of undeclared crate or module `glutin`

error[E0433]: failed to resolve: use of undeclared crate or module `imgui_glow_renderer`
  --> src/main.rs:25:27
   |
25 |     let mut ig_renderer = imgui_glow_renderer::AutoRenderer::initialize(gl, &mut imgui_context)
   |                           ^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `imgui_glow_renderer`

error[E0433]: failed to resolve: use of undeclared crate or module `glutin`
```

I did not modify the source file just copied and pasted.
[dependencies]
imgui = "0.9.0"
glow = "0.10.0"
memoffset = "0.6.4"

[dev-dependencies]
glutin = "0.29.1"
imgui-winit-support = "0.9.0"
image = "0.23"

[features]
# Features here are used to opt-out of compiling code that depends on certain
# OpenGL features. If the features are enabled, the renderer will check that the
# feature is supported before attempting to use it. Only opt-out of any of these
# if you are certain you will only target platforms that lack the corresponding
# feature.
default = [
  "gl_extensions_support",
  "debug_message_insert_support",
  "bind_vertex_array_support",
  "vertex_offset_support",
  "clip_origin_support",
  "bind_sampler_support",
  "polygon_mode_support",
  "primitive_restart_support",
]
# Enable checking for OpenGL extensions
gl_extensions_support = []
# Support for `gl.debug_message_insert`
debug_message_insert_support = []
# Support for `glBindVertexArray`
bind_vertex_array_support = []
# Support for `glDrawElementsBaseVertex`
vertex_offset_support = []
# Support for `GL_CLIP_ORIGIN`
clip_origin_support = []
# Support for `glBindSampler`
bind_sampler_support = []
# Support for `glPolygonMode`
polygon_mode_support = []
# Support for `GL_PRIMITIVE_RESTART`
primitive_restart_support = []
```

**Comment by dbr** [comment]
> BTW that example is not compiling, I copied the `Cargo.toml` and changes the version of `imgui` and `imgui-winit-support` to use just the version number and removed the `path`,

Ah, you just need to move all the dependencies into the main `dependencies` section (the `dev-dependencies` are things only used by `cargo test` and `cargo run --example ...`, not by the main crate), so something like:

```toml
[dependencies]
imgui = "0.9.0"
glow = "0.10.0"
memoffset = "0.6.4"

glutin = "0.29.1"
imgui-winit-support = "0.9.0"
image = "0.23"
```

Also the `features` section is used to disable parts of the glow-renderer code, so you don't need that section of the config

(Note the ability to copy-and-paste an example to get started is something that #664 aims to improve!)

> When I was using `C++` I used `glfw` for windowing and events and `glew` for `gl` stuff. In the link you shared, I see `glow` and `glutin`, if I understand correctly `glow` is like `glew` but what is `glutin`?

I think glfw is basically a combination of winit+glutin+glow,

- [`winit`](https://crates.io/crates/winit) creates OS-level windows
- [`glutin`](https://crates.io/crates/glutin) creates an OpenGL context within that window
- [`glow`](https://crates.io/crates/glow) is bindings to OpenGL to do useful things with that context

The handling of GL extension part like `GLEW` I think is done within `glow`

It's definitely a hard thing to get your head around - quite a lot of interconnected projects, and the graphics ecosystem is still evolving, both in a general industry terms (e.g move to vulkan/metal/wgpu) and moreso in Rust crate world as people work out how best to wrap the often very "non-Rust" graphics API (lots of global state and "just use it correctly or it'll crash" approach to API design) into Rust's "impossible to use wrong" approach - so things like the 0.30 release of glutin was a rewrite to decouple glutin and winit.

**Comment by apoorv569** [comment]
> > BTW that example is not compiling, I copied the `Cargo.toml` and changes the version of `imgui` and `imgui-winit-support` to use just the version number and removed the `path`,
> 
> Ah, you just need to move all the dependencies into the main `dependencies` section (the `dev-dependencies` are things only used by `cargo test` and `cargo run --example ...`, not by the main crate), so something like:
> 
> ```toml
> [dependencies]
> imgui = "0.9.0"
> glow = "0.10.0"
> memoffset = "0.6.4"
> 
> glutin = "0.29.1"
> imgui-winit-support = "0.9.0"
> image = "0.23"
> ```
> 
> Also the `features` section is used to disable parts of the glow-renderer code, so you don't need that section of the config
> 
> (Note the ability to copy-and-paste an example to get started is something that #664 aims to improve!)
> 
> > When I was using `C++` I used `glfw` for windowing and events and `glew` for `gl` stuff. In the link you shared, I see `glow` and `glutin`, if I understand correctly `glow` is like `glew` but what is `glutin`?
> 
> I think glfw is basically a combination of winit+glutin+glow,
> 
>     * [`winit`](https://crates.io/crates/winit) creates OS-level windows
> 
>     * [`glutin`](https://crates.io/crates/glutin) creates an OpenGL context within that window
> 
>     * [`glow`](https://crates.io/crates/glow) is bindings to OpenGL to do useful things with that context
> 
> 
> The handling of GL extension part like `GLEW` I think is done within `glow`
> 
> It's definitely a hard thing to get your head around - quite a lot of interconnected projects, and the graphics ecosystem is still evolving, both in a general industry terms (e.g move to vulkan/metal/wgpu) and moreso in Rust crate world as people work out how best to wrap the often very "non-Rust" graphics API (lots of global state and "just use it correctly or it'll crash" approach to API design) into Rust's "impossible to use wrong" approach - so things like the 0.30 release of glutin was a rewrite to decouple glutin and winit.

I see. After making the changes you mentioned I made some progress, but I still got 1 error,
```
error[E0433]: failed to resolve: use of undeclared crate or module `imgui_glow_renderer`
  --> src/main.rs:25:27
   |
25 |     let mut ig_renderer = imgui_glow_renderer::AutoRenderer::initialize(gl, &mut imgui_context)
   |                           ^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `imgui_glow_renderer`

warning: unused import: `glow::HasContext`
 --> src/main.rs:6:5
  |
6 | use glow::HasContext;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
warning: `sample-hive-imgui-rs` (bin "sample-hive-imgui-rs") generated 1 warning
error: could not compile `sample-hive-imgui-rs` due to previous error; 1 warning emitted
```

adding the `imgui-glow-renderer` `crate` fixed it but it is not listed in the `Cargo.toml` file.

**Comment by dbr** [comment]
Ahh, sorry - you are quite right, you need to add the `imgui-glow-renderer = "0.9.0"` also. The  examples automatically have access to the `imgui-glow-renderer` because it is within that crate (again something #664 will solve)

**Comment by apoorv569** [comment]
> Ahh, sorry - you are quite right, you need to add the `imgui-glow-renderer = "0.9.0"` also. The examples automatically have access to the `imgui-glow-renderer` because it is within that crate (again something #664 will solve)

I see. BTW How to use the `docking` feature in this example? I don't see `docking` in the `imgui_demo_window`.

**Comment by dbr** [comment]
You would change

```
[dependencies]
imgui = "0.9.0"
```

to

```
[dependencies]
imgui = {version = "0.9.0", features = ["docking"]
```

https://github.com/imgui-rs/imgui-rs/issues/683 has example of using the docking API (there's no safe bindings to it in the `imgui` crate yet, except for setting the `DOCKING_ENABLE` flag - anything more needs done with the `imgui::sys` methods which are direct auto-generated bindings to the C++ API)

**Comment by apoorv569** [comment]
> You would change
> 
> ```
> [dependencies]
> imgui = "0.9.0"
> ```
> 
> to
> 
> ```
> [dependencies]
> imgui = {version = "0.9.0", features = ["docking"]
> ```
> 
> #683 has example of using the docking API (there's no safe bindings to it in the `imgui` crate yet, except for setting the `DOCKING_ENABLE` flag - anything more needs done with the `imgui::sys` methods which are direct auto-generated bindings to the C++ API)

I see. Thank you! I think this is solved so I'll close it now.
