### ISSUE TITLE
Wasm is so import today for ruster, so I think it should be a good idea to improve wasm target.

### ISSUE THREAD

**Issue by lencil** [imgui-rs/imgui-rs#703]
There is also some issue when run imgui-rs in web.

**Comment by dbr** [comment]
Agreed - it would be good to get this working smoothly and documented (and tested as part of CI)

There is an existing issue #447 which has some details - including link to a project using an older version of imgui-rs successfully for a WASM project. I think next step is probably to try updating that to latest imgui-rs and see what breaks

**Comment by dbr** [comment]
Shall close this in favour of existing #447 (which I've added the help-wanted label and marked for a future milestone so it hopefully doesn't get forgotten about)
