### ISSUE TITLE
GL viewport doesn't change on resize

### ISSUE THREAD

**Issue by Helyos96** [imgui-rs/imgui-rs#705]
Using imgui-rs 0.10 + imgui-glow-renderer (AutoRenderer) + imgui-winit-support

I noticed that resizing the system window doesn't update the OpenGL context viewport, which messes up my custom GL app underneath the UI. Not that I think that it should or anything, but I was wondering how I can update it ?

I'm using something very similar to [glow_02_triangle.rs](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-glow-renderer/examples/glow_02_triangle.rs)

It looks like the window resize event gets forwarded to winit-support's `handle_window_event` and clearly stuff happens with it but it's not easy to follow everything.

Should I just catch the glutin event and set the viewport to `WindowEvent::Resized(physical_size)` ?

Thanks and sorry for the question-non-issue, I didn't know where else to ask.

**Comment by dbr** [comment]
I *think* this is mainly a glutin(/winit?) thing, so I'm not the best person to answer - but the "catch the glutin event and set the viewport to WindowEvent::Resized(physical_size)" sounds about right

Basically like this: https://github.com/rust-windowing/glutin/blob/v0.29.1/glutin_examples/examples/window.rs plus you'd still need to pass it to `winit_platform.handle_event` so imgui knows about the size change

(one thing to be careful with is the imgui-rs code is still using glutin 0.29, and ["[the 0.30 version] of glutin has been rewritten from the ground and no longer depends on winit"](https://github.com/rust-windowing/glutin/blob/master/CHANGELOG.md#version-0300))

**Comment by Helyos96** [comment]
Thanks dbr, works fine indeed so far. I guess I was confused as to how imgui kept rendering correctly without updating the GL context's viewport. Then again my OpenGL-jitsu is low so there's gotta be something I don't know about that permits this.

**Comment by XZCendence** [comment]
Hey, I'm still having issues with this
