### ISSUE TITLE
How do I read data from a buffer and use it inside imgui-rs?

### ISSUE THREAD

**Issue by javirk** [imgui-rs/imgui-rs#709]
Hi, I have a compute shader that fills a storage buffer at each frame. I want to show some statistics on the contents of that array with imgui every X frames. How could I do that? Is there any example that I could look at related to this?

Thanks!

**Comment by filnet** [comment]
There is no silver bullet I am afraid. 
You'll have to roll out your own code to get the values out of the buffer and pass them to ImGui so it can display them in a text field or whatever fits your need.

**Comment by javirk** [comment]
Yes, I figured that maybe imgui had access to the GPU buffers and there was a ready-to-use method to display them. I guess it has to be done "the hard way" and, even if I'm not sure I know how to do that, the question does not belong to the imgui-rs environment. Thanks, @filnet!
