### ISSUE TITLE
Update to newer versions of glutin

### ISSUE THREAD

**Issue by eyyyyyyy3** [imgui-rs/imgui-rs#723]
Using the newest version of glutin would make imgui-rs more modular as glutin doesn't ship with winit anymore. I mean the glutin rework is already 7 months out and it has to be added sooner or later.

**Comment by sanbox-irl** [comment]
We actually use `glium`, not `glutin`. Once `glium` is updated, we will update. We're basically awaiting its update, which will nicely simplify things on our end too
