### ISSUE TITLE
imgui-glium-renderer has wrong alpha blending settings

### ISSUE THREAD

**Issue by Lateasusual** [imgui-rs/imgui-rs#733]
The winit `Blend::alpha_blending()` used in the glium renderer backend produces an incorrect blending function for our purposes. 

Winit provides (and imgui-glium-renderer uses):
```rust
alpha: BlendingFunction::Addition {
    source: LinearBlendingFactor::SourceAlpha,
    destination: LinearBlendingFactor::OneMinusSourceAlpha
},
```
where the correct function for "overlay" alpha blending should be 
```rust
alpha: BlendingFunction::Addition {
    source: LinearBlendingFactor::One,
    destination: LinearBlendingFactor::OneMinusSourceAlpha,
},
```

**Screenshots**:

Without the change - even though the window background is fully opaque, the drawn imgui windows overwrite the alpha with an incorrect value.
![image](https://github.com/imgui-rs/imgui-rs/assets/24512254/d7e38b7b-9788-4d43-994e-72ba6eca6d2d)

With the change, the window opacity is preserved as expected.
![image](https://github.com/imgui-rs/imgui-rs/assets/24512254/e49a7669-a9a8-4170-a413-3781cf8e007f)

If this is not intentional (which i presume it isn't) *and is not deemed to be a mistake in winit upstream* then I will submit a PR later when I get the chance.

**Comment by sanbox-irl** [comment]
Looking through the code, I believe this is definitely on us. Could you submit that PR?

**Comment by jjungo** [comment]
I have the same issue, #756 solve it on my side.
