### ISSUE TITLE
Is it possible to use SDL2 and docking?

### ISSUE THREAD

**Issue by im-alfa** [imgui-rs/imgui-rs#743]
Hi!

I've been tinkering with the library for a week now, and I was wondering if it's possible to use the viewport example (imgui-winit-glow-renderer-viewports) but using an SDL2 renderer

I think I read somewhere that it was not possible at the moment, but I wonder if someone with more experience and knowledge could confirm this :)

Thanks!

**Comment by dbr** [comment]
Sorry for the slow reply!

There's two parts to the docking branch, docking, and viewports.

The docking feature alone should work with basically any renderer - it works within the common "imgui within a single GL window" type approach.

However the viewports functionality (which lets you have imgui windows as separate OS-level widnows) requires a lot tighter and more extensive integration between imgui and the renderer (to create and destroy OS-level windows, handle resizing per-viewport etc)

Meaning to use the viewport code would require writing a specific integration, similar to the `imgui-winit-glow-renderer-viewports` crate but for SDL2
