### ISSUE TITLE
imgui-rs does not build

### ISSUE THREAD

**Issue by coumcashier** [imgui-rs/imgui-rs#748]
**Describe the bug**
build fails with src/sdlgl3/imgui_impl_sdl_gl3.cpp(11): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No such file or directory

**To Reproduce**
start with a blank project.
cargo add imgui-rs
resulting cargo toml file

        [package]
        name = "imgui-rust-test"
        version = "0.1.0"
        edition = "2021"
    

        # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
        
        [dependencies]
        imgui-rs = "1.47.0"

cargo build

**Expected behavior**
it should build

**Please describe your environment**
 - imgui-rs version 1.47.0
 - win11

**Other information**

log
        
           Compiling imgui-rs v1.47.0
        error: failed to run custom build command for `imgui-rs v1.47.0`
        
        Caused by:
          process didn't exit successfully: `C:\Users\asdf\mysrc\imgui-rust-test\target\debug\build\imgui-rs-f78aaaa6830fe71a\build-script-build` (exit code: 101)      
        ...
          running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "src/cimgui/imgui/" "/I" "src/cimgui/imgui/examples/libs/gl3w/" "/W4" "/FoC:\\Users\\asdf\\mysrc\\imgui-rust-test\\target\\debug\\build\\imgui-rs-5e472dddbba06d31\\out\\src/sdlgl3/imgui_impl_sdl_gl3.o" "/c" "src/sdlgl3/imgui_impl_sdl_gl3.cpp"
          imgui_impl_sdl_gl3.cpp
          src/sdlgl3/imgui_impl_sdl_gl3.cpp(11): fatal error C1083: Cannot open include file: 'SDL2/SDL.h': No such file or directory
          exit code: 2
        
          --- stderr
          thread 'main' panicked at '
        
          Internal error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "src/cimgui/imgui/" "/I" "src/cimgui/imgui/examples/libs/gl3w/" "/W4" "/FoC:\\Users\\asdf\\mysrc\\imgui-rust-test\\target\\debug\\build\\imgui-rs-5e472dddbba06d31\\out\\src/sdlgl3/imgui_impl_sdl_gl3.o" "/c" "src/sdlgl3/imgui_impl_sdl_gl3.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
        
          ', C:\Users\asdf\.cargo\registry\src\index.crates.io-6f17d22bba15001f\gcc-0.3.55\src\lib.rs:1672:5    
          note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sanbox-irl** [comment]
Heya! You appear to be using `imgui-rs`. Our crate is called just `imgui`. I'm going to email whoever owns this crate name to ask them to transfer it to us since this is just misleading.

Edit your package to:

```
imgui = "0.11"
```

and it should work just fine.

Sorry about that confusion, namespace squatters are just the freakin worst!
