### ISSUE TITLE
Switch to dear_imgui

### ISSUE THREAD

**Issue by greaka** [imgui-rs/imgui-rs#753]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
dear_imgui is an official alternative to cimgui, introduced in the 1.90 changelog. It has different tradeoffs to cimgui, which can be found [here](https://github.com/dearimgui/dear_bindings). I just want to make you aware of it.

**Comment by sanbox-irl** [comment]
I'm actually working on this offline! It's a non-trivial change but i've been in touch with the author of it and am excited for it!
