### ISSUE TITLE
InputText.flags(InputTextFlags::ENTER_RETURNS_TRUE) limits input to max of 7

### ISSUE THREAD

**Issue by jestarray** [imgui-rs/imgui-rs#757]
```rs
// THIS LIMITS TEXT INPUT TO 7 MAX!
ui.input_text("##", &mut buff).flags(InputTextFlags::ENTER_RETURNS_TRUE).build();

// this does not!
ui.input_text("##", &mut buff).enter_returns_true(true).build();
```

**Please describe your environment**
 - imgui-rs version [0.11.0]
 - Windows 10(sdl2), Arch Linux(glfw)

The video demonstrates this. I am mashing my keyboard but first example does not go past 7 chars.

https://github.com/imgui-rs/imgui-rs/assets/34615798/4e048c86-a343-48b3-ae26-e9b389f792f4

**Comment by dbr** [comment]
Ah - this seemed very mysterious at first, but it is acting correctly:

By default, the `input_text` widget has `InputTextFlags::CALLBACK_RESIZE` set - this enables `imgui-rs` to automatically resize the buffer as needed. It's [set here](https://github.com/imgui-rs/imgui-rs/blob/e246a334ab38c63a1109726806bc70329c466800/imgui/src/input_widget.rs#L190-L197)

If you set `flags` like that - it *replaces* any existing flags with only `ENTER_RETURNS_TRUE` - disabling the auto-resizing of the text buffer

The important difference being [`fn flags(...)` sets `self.flags = ...`](https://github.com/imgui-rs/imgui-rs/blob/e246a334ab38c63a1109726806bc70329c466800/imgui/src/input_widget.rs#L63) whereas [`fn enter_returns_true` calls `flags.set(...)`](https://github.com/imgui-rs/imgui-rs/blob/e246a334ab38c63a1109726806bc70329c466800/imgui/src/input_widget.rs#L99)

So you could either do

```
ui.input_text("##", &mut buff).flags(InputTextFlags::ENTER_RETURNS_TRUE | InputTextFlags::CALLBACK_RESIZE).build();
```
or use the `enter_returns_true`

I've added a docstring to the `flags` method to note this, as it's easy to overlook!
