### ISSUE TITLE
sdl2 with glow fails to display anything?

### ISSUE THREAD

**Issue by ahhhh6980** [imgui-rs/imgui-rs#760]
I am using the example code provided in https://github.com/imgui-rs/imgui-rs/tree/main/imgui-sdl2-support
I am running cargo on NixOS through a nix shell

![image](https://github.com/imgui-rs/imgui-rs/assets/49384256/f35a1fb8-e9d6-4f2e-9632-ca0d0f9f2669)

**Comment by sanbox-irl** [comment]
Can you tell me anything else here? I'm not familiar with nixOS!

**Comment by ahhhh6980** [comment]
Oh wow, I apologize for not getting back to this. Busy few months.

**Comment by sanbox-irl** [comment]
@ahhhh6980 no problem! feel free to open another issue if you do. I just try to keep the issue list somewhat current
