### ISSUE TITLE
UiBuffer::scratch_txt_two() returns the first pointer to a potentially invalid memory

### ISSUE THREAD

**Issue by salvatorebenedetto** [imgui-rs/imgui-rs#762]
**Describe the bug**
`UiBuffer::scratch_txt_two()` calls push() twice and returns 2 pointers. The problem is that the first pointer is pointing to the old buffer when the second push causes a reallocation due to extend. When building in debug mode on MacOS, rustc 1.75, the old pointer, when there is a resize, will point to the old memory which it seems to be zero out (didn't look into the `extend` implementation) and so the string returned will point to a `\0`, resulting to a null string. The string is later used as label, which will cause `imgui` to assert because IDs can't be null.

This is because the initial capacity, at least on the system I've tried, is 0 and it is doubled everytime. Now, when using `UiBuffer::scratch_txt_two()` if the second txt does not fit into the vector, `extend` will trigger a reallocation and hold pointer will point to the old memory, which if zero out (like in my case), it will be cause a crash.

**To Reproduce**
This is reproducible in debug mode. Use the code in #725 

**Expected behavior**
Library shouldn't return an invalid pointer.

**Screenshots**

**Please describe your environment**
 - imgui-rs 0.11
 - MacOS 14.2.1

**Other information**
One solution I've found is to instead of allocation the buffer with `new()` to call `with_capacity(max_len)` but that requires the method not to be const, which I don't know if it is an acceptable solution.

**Comment by sanbox-irl** [comment]
Fixed in v0.12.0
