### ISSUE TITLE
Spurious console output from imgui-winit-support

### ISSUE THREAD

**Issue by sarchar** [imgui-rs/imgui-rs#766]
KEY INPUT messages appear in the console for every keypress

https://github.com/imgui-rs/imgui-rs/blob/ca05418cb449dadaabf014487c5c965908dfcbdd/imgui-winit-support/src/lib.rs#L486C17-L486C50

**Comment by matt-kimball** [comment]
Indeed - and there is an open PR to fix it:  https://github.com/imgui-rs/imgui-rs/pull/763

**Comment by sanbox-irl** [comment]
Closed as fixed
