### ISSUE TITLE
How to create custom renderer/backend?

### ISSUE THREAD

**Issue by Grant12311** [imgui-rs/imgui-rs#767]
Hi. I need to create a new renderer and backend as the provided options do not fit my needs. My issue is that I cannot seem to find how the backends "link" in to the library. How is the renderer/backend selected and how would I go about creating my own?

**Comment by veeenu** [comment]
Backends are ultimately just users of the library. imgui processes input events and widget creation commands and outputs draw lists, e.g. triangle vertices, texture identifiers, colors etc. It is the responsibility of the backend to 
- interpret data coming from the OS and translate it into input events for imgui
- interpret the draw lists coming from imgui and translate it into draw calls for your renderer

In turn your application uses the functions of those backends as an intermediate layer and is responsible for managing their state.

You can get started by reading the existing backends, reproducing what they do and adapt that to your renderer/input system. Hope that helps!

**Comment by Grant12311** [comment]
Ah, forgive me for forgetting to update this. I ended up taking another approach and integrating egui instead. That had an existing GLFW backend for me to selectively pull from.
