### ISSUE TITLE
Release 0.12 Crate

### ISSUE THREAD

**Issue by jbrd** [imgui-rs/imgui-rs#768]
If the master branch is in a fit state, would it be possible to release it? We could use the updated winit dependency.

If there are known outstanding issues in the master branch, could someone post a summary of what these are? Happy to contribute some help if needed!

**Comment by LegerV** [comment]
Hello Everyone,

First post here, i  wanted to use IMGui-rs on my vulkanalia engine (which actually rely on winit 0.29).

anything i could do to help toward pushing this to a 0.12? 

i see the issue is closed, sorry if i m missing something.

**Comment by dbr** [comment]
[v0.12](https://github.com/imgui-rs/imgui-rs/releases/tag/v0.12.0) is now released!
