### ISSUE TITLE
Characters sent to input text are being repeated

### ISSUE THREAD

**Issue by juliusl** [imgui-rs/imgui-rs#776]
**Describe the bug**

On the main branch, when typing into an input text, the characters are being repeated.

**Env**
- winit 0.29.0,  wayland

**Other information**
Add related issues, suggestions about how to fix, any other context here.

It looks like the issues is because in winit 0.29.0 they removed the ReceivedCharacter event, so now imgui-winit-support calls `add_input_character` inside of KeyboardInput. 

I think the problem is that the KeyboardInput event is emitted twice (press/release) which means `add_input_character` is going to be called twice.

**Comment by juliusl** [comment]
Tried a fix and seems to work, 

```rs
 WindowEvent::KeyboardInput { ref event, .. } => {
                if let Some(txt) = &event.text {
                    if event.state.is_pressed() {
                        for ch in txt.chars() {
                            if ch != '\u{7f}' {
                                io.add_input_character(ch)
                            }
                        }
                    }
                }
```

**Comment by Helyos96** [comment]
Happening on X11 here, but Windows is fine.

**Comment by filnet** [comment]
nit: in the proposed fix, the is pressed check  should be done before extracting the event text.

**Comment by sanbox-irl** [comment]
This is fixed here <https://github.com/imgui-rs/imgui-winit-support/commit/aff79bd2fb09ab26f7c000d14d985880ef32b1ab>
