### ISSUE TITLE
Upgrade imgui to v.1.90 to include resizeable Child

### ISSUE THREAD

**Issue by sbenedetto** [imgui-rs/imgui-rs#778]
With v.1.90, `imgui` supports resizeable child which is a great improvement over manually using splitters.

https://github.com/ocornut/imgui/issues/1710#issuecomment-1791172141
https://github.com/ocornut/imgui/releases/tag/v1.90

It would great if `imgui-rs` could be upgraded to include it.

CC: @dbr

**Comment by sanbox-irl** [comment]
Yeah, we're behind on upgrading. I'm trying to find time this week to make it to it

**Comment by sbenedetto** [comment]
Hey @sanbox-irl  why was this closed? I don't see any PR addressing it.
