### ISSUE TITLE
SDL2 support.

### ISSUE THREAD

**Issue by thelearnerofcode** [imgui-rs/imgui-rs#78]
Is there anyway to use this with SDL2 + raw OpenGL? There are already examples for gfx and glium.

**Comment by Gekkio** [comment]
imgui-rs needs two things:

1. something that handles input events and context/window creation for rendering purposes
2. something that handles rendering (= does some meaningful stuff with vertex buffers and friends)

SDL2, Glutin, and GLFW are libraries that do 1. Glium, gfx, and raw OpenGL can handle 2.

Now, there isn't any special support code for either SDL2 or raw OpenGL in imgui-rs, but there's nothing stopping you from using those. I use SDL2 myself in my Game Boy emulator ([here's the main loop for a screen with a simple GUI](https://github.com/Gekkio/mooneye-gb/blob/1b03d48022cca584867411839d6bbf03d45cb8c0/src/frontend/mod.rs#L221)) and it's quite simple to handle input events and integrate with imgui-rs. Raw OpenGL needs a lot more work, but you should be able to read some upstream imgui demo code for some guidance. Also read [this comment](https://github.com/Gekkio/imgui-rs/issues/49#issuecomment-299114338).

**Comment by michaelfairley** [comment]
Hi! I've recently released glue crates that integrate this library with OpenGL and/or SDL2: https://github.com/michaelfairley/rust-imgui-sdl2 and https://github.com/michaelfairley/rust-imgui-opengl-renderer

**Comment by rasky** [comment]
@michaelfairley's crates work perfectly for me. Any plan on upstreaming them?

**Comment by rasky** [comment]
@Gekkio any time I'm updating imgui-rs, I'm running into version dependency hell because I also need to update the above sdl2/opengl libraries. Any plan on merging them into imgui-rs?

**Comment by dbr** [comment]
Done in #541 :partying_face:
