### ISSUE TITLE
Tracking Winit to v0.30.0

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#781]
Hey all,

I'm updating our winit backend to current winit. This is a fairly large change in winit, which really impacts us, in a funny way, so I'm working on it now.

At a really basic level, bumping for this change is a no-op for us -- I had to rename one single type and switch off one deprecated method.

*However*, we use winit for our windowing in our examples (which makes sense -- we don't want to use sdl2 since it's harder for new users to have all the requirements to compile it). Upgrading *that* is the hard part.

Here's my roadmap for that:

- [x] Simplify our example infrastructure to not return `System`. This will make future example work much easier, since I can adjust everything within `System`.
in-progress PR: https://github.com/sanbox-irl/imgui-rs/tree/better-example-framework
- [ ] Bump Winit version and Update examples

I'll update this issue as I work!

**Comment by julcst** [comment]
For the meantime I created a minimal working fork supporting winit v0.30.4: https://github.com/julcst/imgui-winit-support.git

**Comment by sanbox-irl** [comment]
Closing this as complete in https://github.com/imgui-rs/imgui-winit-support
