### ISSUE TITLE
Interoperability with C SDL2 & render apis

### ISSUE THREAD

**Issue by Kek5chen** [imgui-rs/imgui-rs#784]
**Problem:**
It's currently not possible to take already existing raw pointer objects to integrate with the rust library.

Let's take for example the original example snippets from the imgui repository:

```c
    ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
    ImGui_ImplOpenGL3_Init(glsl_version);
```

These are currently only implemented as rust variants and no unsafe sys implementations exist meaning it's not possible to take up an existing context, which would be really great for debugging.

They are all wrapped and hidden behind rust objects, that all depend on each other and can't be created without following the full init chain.

**Proposed solution:**
I am not all too familiar with the repository, so please propose a better solution, but I'm thinking of new unsafe functions, like for example:

```rust
unsafe fn imgui_sdl2_support::sys::handle_event(...)
unsafe fn imgui_sdl2_support::sys::prepare_frame(...)

// Upstream functions like these would also be nice:

// This would be unsafe for multiple obvious reasons,
// but that's why this should be an unsafe api for us
// people doing weird and gross things with this api.

// it's also currently impossible to work in an existing context.
unsafe fn sdl2::assume_init() -> Sdl // doesn't exist

// you would have to call sdl2::init to get an Sdl context,
// which would fail. there is no unsafe workaround
// this is not needed if it would be possible to use the 
// imgui subsystem init helpers in an unsafe manner
// (sdl2, glow, glium, winit, etc...)
```

**Current Workaround:**
Currently you are forced to use the imgui::sys functions and implement this functionality manually.
I just don't see a reason why this shouldn't be library provided. It feels too restrictive as of now and is pretty much the same code that's already existent in, for example, imgui-sdl2-support, but would be the unsafely implemented version.

**Comment by sanbox-irl** [comment]
We provide glue crates for `sdl2` here: https://github.com/imgui-rs/imgui-sdl2-support

I'm not 100% sure what you're asking, but I suspect these should be sufficient for you
