### ISSUE TITLE
Font Atlas Not Built! - Assertion Failed in `ImGui::ErrorCheckNewFrameSanityChecks`

### ISSUE THREAD

**Issue by p0ryae** [imgui-rs/imgui-rs#788]
**Describe the bug**
I faced an assertion failure in `ImGui::ErrorCheckNewFrameSanityChecks` while incorporating `imgui-rs` to my current project. The full error message is as follows: 

```
test: ./third-party/imgui-master/imgui/imgui.cpp:8882: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->IsBuilt() && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()"' failed.
```

FontAtlas seems to be not building, which causes the failure when the `.frame()` method is called. `imgui.fonts()is_built()` also returns false, and the bool doesn't change throughout the app lifecycle. I also tried to build the textures manually by calling the `build_alpha8_texture()` and `build_rgba32_texture()` methods, but it was no help.

**To Reproduce**
This should explain it well:

```rs

let mut imgui = imgui::Context::create();
let mut platform = imgui_winit_support::WinitPlatform::init(&mut imgui);

if let Some(event_loop) = self.event_loop.take() {
    let _ = event_loop.run(move |event, event_loop| {
        if let Some(ref surface_state) = self.surface_state {
            platform.attach_window(
                imgui.io_mut(),
                &surface_state.window,
                imgui_winit_support::HiDpiMode::Default,
            );

            // .....

            match event {
                Event::WindowEvent { event, .. } => match event {
                    WindowEvent::RedrawRequested => {
                        let ui = imgui.frame();

                        ui.window("Hello world")
                            .size([300.0, 100.0], imgui::Condition::FirstUseEver)
                            .build(|| {
                                ui.text("Hello world!");
                                ui.text("こんにちは世界！");
                                ui.text("This...is...imgui-rs!");
                                ui.separator();
                                let mouse_pos = ui.io().mouse_pos;
                                ui.text(format!(
                                    "Mouse Position: ({:.1},{:.1})",
                                    mouse_pos[0], mouse_pos[1]
                                ));
                            });

                        imgui.render();

                        // etc..
```

**Expected behavior**
The font atlas should be properly built, and no assertion errors should occur.

**Screenshots**
None, since my program crashes.

**Please describe your environment**
 - imgui-rs version: 0.12
 - Operating system: Arch Linux, Kernel 6.10.3-zen1-2-zen
 - imgui-winit-support version: Using a custom fork => https://github.com/julcst/imgui-winit-support

**Other information**
Is there maybe a way to initialize and build the atlas font, just like how it is done for imgui in C++? I couldn't find any information about that in the docs. This thread might be useful: https://github.com/ocornut/imgui/issues/3630

**Comment by mororo18** [comment]
Have you tried something like:
```rust
let font_atlas = imgui.fonts(); 

font_atlas.add_font(&[
    imgui::FontSource::DefaultFontData {
        config: Some(imgui::FontConfig::default()),
    },
]);

let _ = font_atlas.build_rgba32_texture();
```
?

**Comment by sanbox-irl** [comment]
Yeah, as @mororo18 states, you need to build the font that gets rendered. That tends to happen in one of the support crates, such as `imgui-glow-renderer`, but also is trivial to implement yourself.
