### ISSUE TITLE
app with imgui panics! draw_data is empty (unsafe precondition(s) violated: slice::from_raw_parts...)

### ISSUE THREAD

**Issue by Davidos533** [imgui-rs/imgui-rs#789]
**Describe the bug**
whe using this ui
```rust
ui.window("##w")
  //.size([100., 100.], Condition::Once)
  .draw_background(false)
  .title_bar(false)
  .resizable(false)
  .build(|| {
      ui.text("only text");
  });
```

When I try to start app in **debug** mode and **render** imgui ui, constructed from **window without size**, with glow backend (glfw tried too) it's crashes with error: 

```
thread 'main' panicked at library\core\src\panicking.rs:219:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

**This bug fixes if**:

add size to ui build in main.rs line 69
```rust
.size([100., 100.], Condition::Once)
```

**OR**

add _opt-level_ for imgui in Cargo.toml last lines
```TOML
[profile.dev.package.imgui]
opt-level = 2
debug-assertions = false
```

**OR**

jsut execute for run:

```
cargo run --release
```

**To Reproduce**
clone repo: https://github.com/Davidos533/imgui-glow
cd to repo
execute:
```
cargo run
```

**Expected behavior**
App starts you see on screen text rendered by imgui 

**Screenshots**

**Please describe your environment**
 - imgui-rs version 0.12.0
 - Operating system Windows 10 Pro 19045.4651

**Other information**
draw_data is empty
![image](https://github.com/user-attachments/assets/ad07aed5-a394-48f2-85de-3daf0acc506c)
after  get draw_data, code try to get iterator for it and crashes

**Comment by jestarray** [comment]
this is fixed in master iirc: https://github.com/imgui-rs/imgui-rs/pull/779
Since it is not released yet, put this in cargo for a quick fix:
```toml
imgui = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "5d771a8"}
```

**Comment by Davidos533** [comment]
Ok, thanks nice solution, but if you have dependecies that uses old imgui-rs version, you can use 
```rust
[profile.dev.package.imgui]
opt-level = 2
debug-assertions = false
```
for debug 

in release it works fine
