### ISSUE TITLE
Expose Resizeable Child new API

### ISSUE THREAD

**Issue by sbenedetto** [imgui-rs/imgui-rs#798]
**Is your feature request related to a problem? Please describe.**
With v.1.90, imgui supports resizeable child which is a great improvement over manually using splitters.

**Describe the solution you'd like**
Extend the child API to have `resizable()` function.

**Describe alternatives you've considered**
I'm manually using splitters which add a lot of overhead.

**Additional context**
https://github.com/ocornut/imgui/issues/1710#issuecomment-1791172141
https://github.com/ocornut/imgui/releases/tag/v1.90

CC: @sanbox-irl  who is taking care of the imgui update.

**Comment by sanbox-irl** [comment]
Added in #795 , thank you very much for the issue! I'll be updating the rest of the glue crates to have a git dep to this imgui-rs during lunch. i likely won't push a new release of imgui-rs itself though until the selection API -- feel free to switch to a git dep for now yourself to get the new stuff.

Note: you said the `resizable()` function, but actually it's done via flags (`ChildFlags`) passed into `ChildWindow`, not a function
