### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tanis2000** [imgui-rs/imgui-rs#82]
I am trying to get this package to work within an Android application but I've got a problem with the way it uses g++ instead of gcc to compile the cpp files.

My `.cargo/config` file includes the following definitions:

```
[target.armv7-linux-androideabi]
linker = "/Users/tanis/Documents/android-ndk-arm/bin/arm-linux-androideabi-gcc"

[target.aarch64-linux-android]
linker = "/Users/tanis/Documents/android-ndk-arm64/bin/aarch64-linux-android-gcc"

[target.i686-linux-android]
linker = "/Users/tanis/Documents/android-ndk-x86/bin/i686-linux-android-gcc"
```

and it works fine for sdl2 and all the other C-based crates but when it comes to imgui I get the following error:

```
error: failed to run custom build command for `imgui-sys v0.0.15`
process didn't exit successfully: `/Users/tanis/Documents/minigame-rust/target/debug/build/imgui-sys-699678620b97622a/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("armv7-linux-androideabi")
OPT_LEVEL = Some("0")
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("armv7-linux-androideabi")
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CXX_armv7-linux-androideabi = None
CXX_armv7_linux_androideabi = None
TARGET_CXX = None
CXX = None
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CXXFLAGS_armv7-linux-androideabi = None
CXXFLAGS_armv7_linux_androideabi = None
TARGET_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "arm-linux-androideabi-g++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-march=armv7-a" "-march=armv7-a" "-mfpu=vfpv3-d16" "-mfloat-abi=softfp" "-o" "/Users/tanis/Documents/minigame-rust/target/armv7-linux-androideabi/debug/build/imgui-sys-baa2353af33cf674/out/third-party/cimgui/cimgui/cimgui.o" "-c" "third-party/cimgui/cimgui/cimgui.cpp"


failed to execute command: No such file or directory (os error 2)
Is `arm-linux-androideabi-g++` not installed?



--- stderr
thread 'main' panicked at 'explicit panic', /Users/tanis/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.51/src/lib.rs:1239:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I suppose this is because I've only defined where to find gcc but there's no indication of where g++ lives. Is there any way to achieve that either with cargo or any other way?

**Comment by Gekkio** [comment]
Sorry, I don't have any recent experience of cross-compiling for Android, but here are some notes that might help you:

* imgui is C++ and therefore needs a C++ compiler. You can't compile it with just a C compiler
* I don't think imgui needs STL, but I might be wrong and you might need to fiddle with the Android C++ settings (stlport, static vs shared, etc... can't remember details but there were several settings)
* I remember that at least some time ago a standalone toolchain was needed in some cross-compilation scenarios
* You'll need to use the master branch version, because the current release (0.0.15) doesn't support OpenGL ES. Preliminary support for OpenGL ES is in master, but hasn't been tested on Android yet

Good luck, and if you get it to work, please report back 😄

**Comment by tanis2000** [comment]
Thanks for the reply @Gekkio. It looks like Cargo isn’t passing down its config settings to dependencies as they get compiled before my build.rs kicks in so I have no tidy way of letting your crate know about my environment.

I kind of solved it by passing CC, CXX and AR in the command line calling cargo build. It’s ugly but it gets the job done :-P

**Comment by kingofoz** [comment]
Hi @tanis2000 
Can you show me how to compile it for Android?

**Comment by tanis2000** [comment]
@kingofoz here's the script that I'm using to get the whole thing working: https://github.com/tanis2000/minigame-rust/blob/master/android_make.sh
It's tailored for my project but I guess you can get the part that you need out of it.

**Comment by kingofoz** [comment]
Hi @tanis2000 
Thanks for the quick response! I will try it ASAP. By the way, what kind of game is minigame-rust? I am a rust learner, and want to write a game by rust.

**Comment by tanis2000** [comment]
So far it's just a partial port of my C++ engine. I'm experimenting with Rust for game development so that's pretty much just a test bed for the time being. I plan on turning it into a simple shoot em up game as soon as I consider the whole engine ready, but since it's juts a hobby project it's taking a while to get there :)

On the other hand, I managed to get hot code reloading and cross-platform support working on iOS, Android, macOS, Windows and Linux which is already something ;)

**Comment by kingofoz** [comment]
I see. Thanks @tanis2000 
By the way, can you show me your C++ engine? :)

**Comment by tanis2000** [comment]
I'm planning on releasing the engine as an open source project, but I still feel it's not mature enough for public user consumption. It's fine for my needs as it's custom tailored to the way I code, so I'm not even sure it would benefit anyone to have yet another game engine out there in the wild :)
