### ISSUE TITLE
vulkan support

### ISSUE THREAD

**Issue by kingofoz** [imgui-rs/imgui-rs#91]
hi @Gekkio 
Do you have a plan to add vulkan support?

**Comment by kingofoz** [comment]
any comments?

**Comment by Gekkio** [comment]
`gfx` already supports Vulkan, so it shouldn't be too difficult to use it with imgui-rs. However, right now imgui-gfx-renderer doesn't include Vulkan-compatible shaders, so some manual work is needed. Once the big changes in `gfx` are finally released, I plan to make imgui-gfx-renderer easier to use with alternative backends (Vulkan, DX, possibly Metal...).

I've also considered writing a `vulkano`-based renderer, but I don't really know Vulkan at all so it's not going to happen very soon.

**Comment by CHAM0** [comment]
Hello @Gekkio 
Do you plan to add Vulkano  backends soon ?

**Comment by Gekkio** [comment]
Sorry, no plans right now because I still haven't found time to learn Vulkan, and no pull requests have appeared. Once the new LL redesign of gfx gets a proper crates.io release, the gfx renderer will be updated to use it and you should be able to at least target Vulkan as a backend with it.

**Comment by Benjamin-L** [comment]
I wrote [a backend](https://git.chronicembetterment.org/benjamin/imgui-gfx-hal/) for gfx-hal a while ago, if anybody is interested in taking a look. I am not super experienced with vulkan though, so I'm pretty sure it's not optimal.

**Comment by kollapsderwellenfunktion** [comment]
hello,

i've updated bejamins code to work with current dependencies. you can add textures too. but it's just a hack for now. 

https://github.com/kollapsderwellenfunktion/imgui-backend-gfx-hal

**Comment by cheako** [comment]
https://www.reddit.com/r/rust/comments/crb7q7/success_i_have_a_working_setup_of_imgui_on_vulkan/

I think this can be closed?

**Comment by dbr** [comment]
Closing, can be handled by a thirdparty crate like https://github.com/adrien-ben/imgui-rs-vulkan-renderer
